@extends('layouts.guest')
@php
$questions=[['shopping-cart','Comment commander ?','Parcourez le catalogue ou recherchez le produit souhaité. Ajoutez-le au panier, choisissez la quantité et la livraison, puis validez votre commande.'],['credit-card','Quels paiements acceptez-vous ?','OVANIE accepte Wave, Orange Money, MTN MoMo, Moov Money, la carte bancaire lorsqu’elle est activée et le paiement à la livraison selon éligibilité.'],['map-pin','Comment suivre ma commande ?','Utilisez la page Suivi de commande ou rendez-vous dans votre espace client, rubrique Mes commandes.'],['map','Comment modifier une adresse ?','Avant l’expédition, modifiez votre adresse depuis votre compte ou contactez rapidement le service client.'],['wallet','Puis-je payer à la livraison ?','Oui, lorsque cette option est disponible pour votre zone, le vendeur et la commande.'],['badge-dollar-sign','Comment utiliser une carte cadeau ?','Saisissez le code de la carte dans le champ dédié au moment du paiement. Le montant disponible est déduit du total.'],['undo-2','Comment retourner un produit ?','Consultez la page Retours et remboursements puis ouvrez une demande pour la commande concernée.']];
$cats=[['shopping-bag','Commandes'],['credit-card','Paiements'],['truck','Livraison'],['package','Retours'],['user','Compte'],['gift','Cartes OVANIE'],['briefcase-business','OVANIE Pro'],['store','Vendeur']];
@endphp
@section('title','FAQ OVANIE')
@push('styles')<link rel="stylesheet" href="{{asset('css/support-pages.css')}}?v={{filemtime(public_path('css/support-pages.css'))}}"><style>.fq-hero{min-height:380px;padding:48px;display:flex;align-items:center;border-radius:17px;background:#062d65 url('{{asset('images/support-pages/support-hero.png')}}') center/cover;color:#fff}.fq-hero>div{width:48%}.fq-hero h1{font-size:55px;margin:0 0 15px}.fq-hero h1 em{color:#ff6500;font-style:normal}.fq-hero p{font-size:20px;line-height:1.5}.fq-search{height:55px;padding:0 18px;display:flex;align-items:center;gap:12px;border-radius:7px;background:#fff;color:#0a356c}.fq-search input{width:100%;border:0;outline:0}.fq-cats{display:grid;grid-template-columns:repeat(8,1fr);gap:8px;margin:20px 0}.fq-cats a{padding:20px 8px;text-align:center;border:1px solid #dce5ef;border-radius:11px;background:#fff;color:#071a3d;text-decoration:none}.fq-cats i{width:40px;color:#073d81}.fq-cats b{display:block;margin-top:8px;font-size:10px}.fq-list details{border-bottom:1px solid #e1e8f0}.fq-list summary{padding:20px;display:flex;gap:22px;align-items:center;cursor:pointer;list-style:none;font-weight:800}.fq-list summary i{width:38px;height:38px;padding:8px;border-radius:8px;background:#f1f5fa;color:#073d81}.fq-list summary span{margin-left:auto}.fq-list p{margin:0;padding:0 80px 20px;color:#607089;font-size:12px;line-height:1.6}@media(max-width:800px){.fq-cats{grid-template-columns:repeat(2,1fr)}.fq-hero>div{width:100%}.fq-hero{padding:28px;background-position:65%}.fq-hero h1{font-size:40px}}</style>@endpush
@section('content')<main class="sp"><div class="sp-shell"><nav class="sp-crumb"><a href="{{route('home')}}">Accueil</a><span>›</span><a href="{{route('help.center')}}">Centre d’aide</a><span>›</span><b>FAQ</b></nav>
<section class="fq-hero"><div><h1>FAQ <em>OVANIE</em></h1><p>Retrouvez rapidement les réponses aux questions les plus fréquentes.</p><label class="fq-search"><i data-lucide="search"></i><input id="faqFilter" type="search" placeholder="Comment pouvons-nous vous aider ?"></label><a class="fq-help-link" href="{{route('help.center')}}">Aller au Centre d’aide complet →</a></div></section>
<section class="fq-cats">@foreach($cats as $item)<a href="#questions"><i data-lucide="{{$item[0]}}"></i><b>{{$item[1]}}</b></a>@endforeach</section>
<section id="questions" class="sp-panel fq-list">@foreach($questions as $i=>$item)<details data-question="{{Str::lower($item[1].' '.$item[2])}}" {{$i===0?'open':''}}><summary><i data-lucide="{{$item[0]}}"></i>{{$i+1}}. {{$item[1]}}<span>⌄</span></summary><p>{{$item[2]}}</p></details>@endforeach</section>
<section class="sp-support"><i data-lucide="headset"></i><div><h2>Besoin d’aide supplémentaire ?</h2><p>Explorez le centre d’aide ou contactez notre équipe.</p></div><a href="{{route('contact.index')}}">Nous écrire →</a></section>
</div></main>@endsection
@push('scripts')<script>document.getElementById('faqFilter')?.addEventListener('input',function(){const q=this.value.toLowerCase();document.querySelectorAll('[data-question]').forEach(el=>el.hidden=!el.dataset.question.includes(q))})</script>@endpush
@push('styles')<style>.fq-hero{background-color:#062d65;background-image:linear-gradient(90deg,rgba(6,45,101,.3),rgba(6,45,101,0)),url('{{asset('images/support-pages/support-hero.png')}}');background-repeat:no-repeat;background-position:center,right center;background-size:100% 100%,auto 100%}@media(max-width:800px){.fq-hero{background-position:center,right center;background-size:100% 100%,auto 100%}}</style>@endpush
@push('styles')<style>.fq-hero{background-image:linear-gradient(90deg,rgba(3,34,75,.28),rgba(3,34,75,0)),url('{{asset('images/support-pages/support-hero.png')}}');background-size:100% 100%;background-position:center}.fq-help-link{display:inline-block;margin-top:17px;color:#fff;font-size:11px;font-weight:800;text-decoration:underline;text-underline-offset:4px}@media(max-width:800px){.fq-hero{background-size:cover;background-position:center}}</style>@endpush
