@extends('layouts.guest')
@php
$isTracking=$page==='tracking'; $isGuarantee=$page==='guarantee';
$title=$isTracking?'Suivi de commande':($isGuarantee?'Garantie acheteur OVANIE':'Centre d’aide OVANIE');
$hero=$isTracking?'tracking-hero.png':($isGuarantee?'guarantee-hero.png':'support-hero.png');
$categories=[['shopping-bag','Commandes','Suivi, modifications et informations sur vos commandes.'],['credit-card','Paiements','Moyens de paiement, sécurité et remboursements.'],['truck','Livraison','Frais, délais, suivi et zones desservies.'],['package','Retours','Conditions, procédure et remboursements.'],['user','Compte','Informations personnelles et sécurité.'],['gift','Cartes OVANIE','Cartes cadeaux, cartes virtuelles et utilisation.'],['briefcase-business','OVANIE Pro','Devis, achats en gros et commandes professionnelles.'],['store','Vendeur','Devenir vendeur et gérer sa boutique.']];
$faqs=[['Comment commander ?','Recherchez un produit, choisissez la quantité, ajoutez-le au panier puis validez votre adresse et votre paiement.'],['Quels paiements acceptez-vous ?','Wave, Orange Money, MTN MoMo, Moov Money, carte bancaire lorsqu’elle est activée et paiement à la livraison pour les commandes éligibles.'],['Comment suivre ma commande ?','Utilisez la page de suivi ou consultez Mes commandes depuis votre espace client.'],['Comment modifier une adresse ?','Modifiez-la avant l’expédition depuis votre compte ou contactez rapidement notre équipe.'],['Puis-je payer à la livraison ?','Oui, lorsque cette option est disponible pour votre zone et votre commande.'],['Comment utiliser une carte cadeau ?','Saisissez le code de la carte au moment du paiement. Le montant disponible sera déduit du total.'],['Comment retourner un produit ?','Consultez la page Retours et remboursements puis ouvrez une demande pour la commande concernée.']];
@endphp
@section('title',$title)
@push('styles')<link rel="stylesheet" href="{{asset('css/support-pages.css')}}?v={{filemtime(public_path('css/support-pages.css'))}}">@endpush
@section('content')
<main class="sp"><div class="sp-shell"><nav class="sp-crumb"><a href="{{route('home')}}">Accueil</a><span>›</span><b>{{$title}}</b></nav>
@if(!$isTracking && !$isGuarantee)
<section class="sp-help-hero"><h1>Comment pouvons-nous<br><em>vous aider ?</em></h1><p>Trouvez rapidement des réponses à vos questions.</p><label><i data-lucide="search"></i><input id="helpSearch" type="search" placeholder="Rechercher une question, un sujet, une commande..."></label></section>
<section class="sp-categories">@foreach($categories as $item)<a href="{{route('faq')}}"><i data-lucide="{{$item[0]}}"></i><h2>{{$item[1]}}</h2><p>{{$item[2]}}</p><b>→</b></a>@endforeach</section>
<section class="sp-panel"><div class="sp-head"><h2>Questions fréquentes</h2><a href="{{route('faq')}}">Voir toutes les FAQ →</a></div><div class="sp-faq two">@foreach($faqs as $item)<details><summary>{{$item[0]}}<span>⌄</span></summary><p>{{$item[1]}}</p></details>@endforeach</div></section>
@elseif($isTracking)
<section class="sp-photo-hero" style="--hero:url('{{asset('images/support-pages/'.$hero)}}')"><div><h1>Suivez votre commande<br>en temps réel avec <em>OVANIE</em></h1><p>Entrez vos informations pour connaître l’état de votre commande.</p><div class="sp-hero-badges"><span><i data-lucide="truck"></i>Livraison rapide</span><span><i data-lucide="shield-check"></i>Paiement sécurisé</span><span><i data-lucide="package-check"></i>Produits de qualité</span><span><i data-lucide="headset"></i>Support dédié</span></div></div></section>
<section class="sp-track-card"><span class="sp-round"><i data-lucide="package-search"></i></span><h2>Rechercher votre commande</h2><p>Renseignez votre numéro de commande et l’adresse e-mail ou le téléphone associé.</p><form method="GET" action="{{route('orders.index')}}"><label>Numéro de commande<input name="q" required placeholder="Exemple : OVN-2026-000123"></label><label>Téléphone ou e-mail<input name="contact" required placeholder="07 07 07 07 07 ou client@email.com"></label><button type="submit"><i data-lucide="search"></i> Suivre ma commande</button></form><div class="sp-login"><span>Vous êtes déjà connecté ? Consultez toutes vos commandes.</span><a href="{{route('orders.index')}}">Aller à mon espace client →</a></div></section>
<h2 class="sp-center-title">Comment ça fonctionne ?</h2><section class="sp-steps">@foreach([['contact-round','Entrez vos informations'],['search','Vérification'],['truck','Suivi en temps réel'],['shield-check','Livraison']] as $i=>$item)<article><span>{{$i+1}}</span><i data-lucide="{{$item[0]}}"></i><h3>{{$item[1]}}</h3><p>{{['Renseignez la référence et vos coordonnées.','Nous vérifions les informations de la commande.','Consultez l’état et les étapes de livraison.','Recevez votre commande à l’adresse indiquée.'][$i]}}</p></article>@endforeach</section>
@else
<section class="sp-photo-hero" style="--hero:url('{{asset('images/support-pages/'.$hero)}}')"><div><h1>Achetez en confiance<br>avec <em>OVANIE</em></h1><p>Votre satisfaction est notre priorité. Une expérience d’achat sûre, transparente et fiable.</p><div class="sp-hero-badges"><span><i data-lucide="shield-check"></i>Plateforme sécurisée</span><span><i data-lucide="badge-check"></i>Vendeurs vérifiés</span><span><i data-lucide="package-check"></i>Produits contrôlés</span><span><i data-lucide="headset"></i>Support dédié</span></div></div></section>
<section class="sp-panel"><h2>La garantie OVANIE en 5 engagements</h2><div class="sp-commitments">@foreach([['lock-keyhole','Paiement sécurisé','Vos paiements sont protégés.'],['badge-check','Produits contrôlés','Qualité vérifiée avant expédition.'],['truck','Commande suivie','Suivi jusqu’à la livraison.'],['headset','Assistance dédiée','Une équipe à votre écoute.'],['scale','Gestion des litiges','Une solution équitable en cas de problème.']] as $i=>$item)<article><span>{{$i+1}}</span><i data-lucide="{{$item[0]}}"></i><h3>{{$item[1]}}</h3><p>{{$item[2]}}</p></article>@endforeach</div></section>
<section class="sp-panel"><h2>Pourquoi acheter sur OVANIE ?</h2><div class="sp-benefits">@foreach([['thumbs-up','Des vendeurs de confiance'],['award','Des produits de qualité'],['shield-check','Vos achats protégés'],['headset','Un service client à votre écoute']] as $item)<div><i data-lucide="{{$item[0]}}"></i><b>{{$item[1]}}</b></div>@endforeach</div></section>
<section class="sp-panel"><h2>Comment nous protégeons vos achats</h2><div class="sp-steps small">@foreach([['credit-card','Paiement sécurisé'],['clipboard-check','Vérification'],['package-check','Expédition suivie'],['user-check','Réception contrôlée'],['shield','OVANIE intervient']] as $item)<article><i data-lucide="{{$item[0]}}"></i><h3>{{$item[1]}}</h3></article>@endforeach</div></section>
@endif
<section class="sp-support"><i data-lucide="headset"></i><div><h2>Besoin d’aide supplémentaire ?</h2><p>Notre équipe vous répond rapidement.</p></div><a href="{{route('contact.index')}}">Nous contacter →</a></section>
</div></main>
@endsection
