@extends('layouts.guest')
@php
$m=['mission'=>['Notre mission','Faciliter, connecter et faire grandir le secteur du BTP en Côte d’Ivoire.','mission-hero.png'],'values'=>['Nos valeurs','Des valeurs solides pour bâtir la confiance des professionnels et des particuliers.','values-hero.png'],'vendor-terms'=>['Conditions vendeurs OVANIE','Un cadre clair pour vendre durablement et en toute confiance.','vendor-terms-hero.png'],'report'=>['Signaler un problème','Une difficulté sur votre commande, votre paiement, votre livraison ou votre compte ?','report-hero.png']][$page];
$vals=[['shield-check','Confiance','Des relations durables basées sur l’intégrité et la fiabilité.'],['award','Qualité','Des produits conformes pour des chantiers performants.'],['search','Transparence','Des prix clairs et une communication ouverte.'],['users','Proximité','Une écoute attentive des besoins du terrain.'],['lightbulb','Innovation utile','Des solutions réellement simples et efficaces.'],['hard-hat','Engagement terrain','Une compréhension concrète du BTP ivoirien.']];
@endphp
@section('title',$m[0].' | OVANIE')
@section('styles')<link rel="stylesheet" href="{{asset('css/institutional-pages.css')}}">@endsection
@section('content')<main class="ip-page ip-page--{{$page}}"><div class="ip-shell"><nav class="ip-crumb"><a href="{{route('home')}}">Accueil</a><span>›</span><strong>{{$m[0]}}</strong></nav>
@if($page==='mission')
<section class="mission-hero"><div class="mission-copy"><h1>Notre mission</h1><i></i><h2>{{$m[1]}}</h2><p>OVANIE modernise l’approvisionnement en matériaux, équipements et solutions BTP en offrant une marketplace fiable, innovante et accessible à tous.</p><blockquote>Nous croyons en un secteur du BTP plus efficace, plus transparent et plus proche de chaque acteur.</blockquote></div><div class="mission-picture" style="background-image:url('{{asset('images/institutional-pages/'.$m[2])}}')"><div class="mission-overlay">@foreach([['users','Connecter'],['badge-check','Simplifier'],['shield-check','Sécuriser'],['chart-no-axes-combined','Contribuer']] as $x)<div><i data-lucide="{{$x[0]}}"></i><strong>{{$x[1]}}</strong></div>@endforeach</div></div></section>
<h2 class="ip-title">Ce qui guide notre mission</h2><div class="ip-grid ip-grid--5">@foreach(array_slice($vals,0,5) as $x)<x-ip-card :item="$x"/>@endforeach</div><section class="ip-stats"><h2>Notre ambition</h2><div>@foreach([['BTP','Une marketplace spécialisée'],['Vendeurs','Des partenaires professionnels'],['Catalogue','Des solutions pour les chantiers'],['Livraison','Une couverture adaptée aux besoins'],['Service','Un accompagnement client dédié']] as $s)<p><strong>{{$s[0]}}</strong><span>{{$s[1]}}</span></p>@endforeach</div></section><x-ip-cta title="Ensemble, construisons l’avenir du BTP en Côte d’Ivoire." />
@else
<section class="ip-hero" style="background-image:url('{{asset('images/institutional-pages/'.$m[2])}}')"><div class="ip-hero__copy"><h1>{{$m[0]}}</h1><h2>{{$m[1]}}</h2>@if($page==='report')<p>Déclarez votre problème en quelques minutes afin que notre équipe puisse vous aider rapidement.</p><div class="hero-actions"><a class="ip-btn" href="#signalement">Envoyer un signalement</a><a class="ip-btn ip-btn--outline" href="{{route('contact.index')}}">Contacter le support</a></div>@endif</div></section>
@if($page==='values')
<h2 class="ip-title ip-title--left">Les valeurs qui guident OVANIE</h2><div class="ip-grid ip-grid--6">@foreach($vals as $x)<x-ip-card :item="$x"/>@endforeach</div><h2 class="ip-title ip-title--left">Ce que cela signifie pour nos clients et partenaires</h2><div class="ip-grid ip-grid--3">@foreach([['lock','Des achats en toute sécurité','Paiements sécurisés et produits vérifiés.'],['badge-check','Un service fiable et réactif','Livraison, suivi et support à chaque étape.'],['handshake','Un partenaire de long terme','Des relations basées sur la confiance.']] as $x)<x-ip-card :item="$x"/>@endforeach</div><section class="ip-band">@foreach([['shield-check','Produits vérifiés'],['lock','Paiement sécurisé'],['truck','Livraison organisée'],['headphones','Assistance humaine']] as $x)<div><i data-lucide="{{$x[0]}}"></i><strong>{{$x[1]}}</strong><span>Notre engagement au quotidien.</span></div>@endforeach</section><blockquote class="ip-quote">Chez OVANIE, la confiance, la qualité des solutions et l’engagement construisent les infrastructures durables de demain.</blockquote><x-ip-cta title="Prêt à construire avec OVANIE ?" />
@elseif($page==='vendor-terms')
<h2 class="ip-title">Nos principes</h2><div class="ip-grid ip-grid--5">@foreach([['shield-check','Confiance'],['award','Qualité'],['handshake','Partenariat'],['lock','Sécurité'],['chart-no-axes-combined','Performance']] as $x)<x-ip-card :item="[$x[0],$x[1],'Un engagement professionnel et transparent.']"/>@endforeach</div><h2 class="ip-title">Conditions générales</h2><div class="ip-grid ip-grid--3 terms-grid">@foreach([['user-check','Éligibilité'],['store','Ouverture de boutique'],['package','Produits & services'],['truck','Logistique & livraison'],['wallet-cards','Paiement & reversement'],['percent','Commissions'],['headphones','Service client'],['ban','Interdictions'],['triangle-alert','Sanctions'],['file-check','Responsabilités'],['file-pen-line','Modification des conditions'],['handshake','Résiliation']] as $n=>$x)<article class="ip-card term-card"><b class="term-no">{{str_pad($n+1,2,'0',STR_PAD_LEFT)}}</b><i data-lucide="{{$x[0]}}"></i><div><h3>{{$x[1]}}</h3><ul><li>Informations complètes et exactes</li><li>Respect des règles OVANIE</li><li>Service fiable et professionnel</li><li>Conformité réglementaire</li></ul></div></article>@endforeach</div><section class="ip-band ip-band--light"><div><strong>Notre engagement envers vous</strong><span>Une plateforme et un support dédiés.</span></div><div><strong>Support dédié</strong><span>Une équipe disponible.</span></div><div><strong>Formation continue</strong><span>Des conseils utiles.</span></div><div><strong>Écosystème BTP</strong><span>Un réseau de partenaires.</span></div></section><x-ip-cta title="Prêt à développer votre business avec OVANIE ?" />
@else
<section id="signalement" class="report-layout"><form class="ip-form" action="{{route('contact.send')}}" method="POST">@csrf<h2>Décrivez votre problème</h2><p>Plus vous fournissez d’informations, plus nous pourrons vous aider rapidement.</p><label>1. Type de problème</label><div class="issue-grid">@foreach([['shopping-bag','Commande'],['credit-card','Paiement'],['truck','Livraison'],['package','Produit'],['user','Compte'],['gift','Carte OVANIE'],['briefcase','OVANIE Pro'],['message-circle','Autre problème']] as $x)<label><input type="radio" name="subject" value="{{$x[1]}}" required><i data-lucide="{{$x[0]}}"></i><span>{{$x[1]}}</span></label>@endforeach</div><div class="ip-form-grid"><div class="ip-field"><label>Nom complet *</label><input name="name" required></div><div class="ip-field"><label>Téléphone *</label><input name="phone" required></div><div class="ip-field"><label>E-mail *</label><input name="email" type="email" required></div><div class="ip-field"><label>Numéro de commande</label><input></div><div class="ip-field ip-field--full"><label>Décrivez votre problème *</label><textarea name="message" required></textarea></div><div class="ip-field ip-field--full file-drop"><i data-lucide="cloud-upload"></i> Glissez vos fichiers ici ou cliquez pour parcourir</div><button class="ip-btn ip-field--full">Envoyer mon signalement →</button></div></form><aside class="report-side"><section><h2>Problèmes les plus fréquents</h2>@foreach(['Produit endommagé ou défectueux','Mauvais produit reçu','Retard de livraison','Paiement non abouti','Difficulté de connexion au compte'] as $x)<p>{{$x}} <b>›</b></p>@endforeach</section><section><h2>Que se passe-t-il ensuite ?</h2>@foreach(['Réception du signalement','Analyse du dossier','Suivi par notre équipe','Proposition de solution'] as $n=>$x)<div class="timeline"><b>{{$n+1}}</b><span><strong>{{$x}}</strong><small>Notre équipe vous tient informé.</small></span></div>@endforeach</section><section><h2>Besoin d’aide immédiate ?</h2><a class="phone" href="tel:{{ config('public_contact.phone_e164', '+2250161780000') }}">{{ config('public_contact.phone_display', '01 61 78 00 00') }}</a><p><a href="mailto:{{ config('public_contact.email', 'contact@ovanie.com') }}">{{ config('public_contact.email', 'contact@ovanie.com') }}</a></p></section></aside></section>
@endif @endif
</div></main>@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>window.lucide?.createIcons())</script>@endpush
