@extends('layouts.guest')
@php
$pages=[
'privacy'=>['title'=>'Politique de confidentialité','intro'=>'OVANIE protège vos données personnelles et s’engage à une utilisation responsable, transparente et sécurisée de vos informations.','icon'=>'lock-keyhole','sections'=>[
['Données collectées','Nous traitons uniquement les informations utiles à nos services : identité, coordonnées, adresse, commandes, paiements, livraisons, échanges avec le support et données techniques de connexion.'],
['Pourquoi nous collectons ces données','Ces informations permettent de gérer votre compte, traiter les commandes, organiser la livraison, sécuriser les paiements, répondre à vos demandes et améliorer votre expérience.'],
['Partage limité des informations','Vos données ne sont pas vendues. Elles sont transmises uniquement aux prestataires nécessaires au paiement, à la livraison, à l’hébergement ou au support, dans la limite de leur mission.'],
['Sécurité et protection des données','OVANIE applique des mesures techniques et organisationnelles destinées à prévenir l’accès non autorisé, la perte, l’altération ou la divulgation des informations.'],
['Cookies et navigation','Les cookies nécessaires assurent le fonctionnement du site. D’autres outils peuvent mesurer la performance ou mémoriser vos préférences selon les choix disponibles dans votre navigateur.'],
['Vos droits','Vous pouvez demander l’accès, la rectification, la suppression ou la limitation de certaines données, et vous opposer à certains traitements conformément à la réglementation applicable.'],
['Conservation des données','Les données sont conservées pendant la durée nécessaire au service, puis archivées ou supprimées selon les obligations légales, comptables, fiscales et de sécurité.'],
['Contact confidentialité','Pour exercer un droit ou poser une question, contactez OVANIE via le formulaire de contact en précisant l’objet de votre demande.']]],
'terms'=>['title'=>'Conditions générales d’utilisation','intro'=>'Les présentes CGU encadrent l’accès et l’utilisation de la plateforme OVANIE ainsi que des services associés.','icon'=>'scale','sections'=>[
['Objet','Ces conditions définissent les droits et obligations applicables aux visiteurs, clients, vendeurs et utilisateurs des services OVANIE.'],['Accès et utilisation du site','L’utilisateur s’engage à utiliser la plateforme de façon licite, loyale et sans perturber son fonctionnement.'],['Création de compte','Les informations fournies doivent être exactes. L’utilisateur protège ses identifiants et signale rapidement toute utilisation non autorisée.'],['Produits, prix et disponibilité','Les caractéristiques, prix et disponibilités sont présentés avec soin et confirmés au cours du processus de commande.'],['Commandes','Une commande est enregistrée après validation des informations nécessaires et confirmation selon le moyen de paiement choisi.'],['Paiement','Les paiements sont traités par les moyens affichés lors de la commande. OVANIE ne conserve pas les données bancaires sensibles.'],['Livraison','Les frais et délais dépendent de l’adresse, du poids, du volume, de la disponibilité et de la solution de transport adaptée.'],['Retours et remboursements','Les retours éligibles suivent la procédure et les délais présentés sur la page Retours et remboursements.'],['Responsabilités','Chaque utilisateur reste responsable des informations qu’il communique et du respect de la réglementation applicable.'],['Propriété intellectuelle','Les marques, textes, visuels et éléments de la plateforme sont protégés. Toute reproduction non autorisée est interdite.'],['Protection des données','Le traitement des données est décrit dans la Politique de confidentialité OVANIE.'],['Modification des CGU','OVANIE peut mettre à jour ces conditions. La version publiée sur cette page est la version applicable.'],['Droit applicable et contact','Les présentes conditions sont soumises au droit ivoirien. Pour toute question, contactez le support OVANIE.']]],
'legal-notice'=>['title'=>'Mentions légales','intro'=>'Informations officielles relatives à l’édition, l’exploitation et l’utilisation de la plateforme OVANIE.','icon'=>'landmark','sections'=>[
['Éditeur de la plateforme','La plateforme OVANIE est éditée et exploitée par OVANIE. Siège de contact : Marcory, Zone 4, Abidjan, Côte d’Ivoire. E-mail : '.config('public_contact.email', 'contact@ovanie.com').'. Téléphone : '.config('public_contact.phone_display', '01 61 78 00 00').'.'],['Direction de la publication','La direction de la publication est assurée par le représentant légal d’OVANIE.'],['Hébergement','Les services techniques peuvent être hébergés auprès de prestataires spécialisés répondant aux exigences de disponibilité et de sécurité de la plateforme.'],['Propriété intellectuelle','Le nom OVANIE, son identité visuelle, les contenus, interfaces, bases de données et éléments graphiques sont protégés. Toute utilisation non autorisée est interdite.'],['Responsabilité','OVANIE met en œuvre les moyens nécessaires pour fournir des informations fiables, sans pouvoir garantir l’absence permanente d’erreurs ou d’interruptions techniques.'],['Liens externes','La plateforme peut contenir des liens vers des services tiers. OVANIE n’est pas responsable de leur contenu ni de leurs pratiques.'],['Données personnelles','Le traitement des données personnelles est détaillé dans la Politique de confidentialité accessible depuis le footer.'],['Droit applicable','Les présentes mentions sont régies par le droit ivoirien. Les utilisateurs peuvent contacter OVANIE avant toute démarche contentieuse.']]]];
$d=$pages[$page];
@endphp
@section('title',$d['title'].' | OVANIE')
@section('styles')<link rel="stylesheet" href="{{asset('css/institutional-pages.css')}}">@endsection
@section('content')
<main class="lp-page lp-page--{{$page}}"><div class="lp-shell"><nav class="ip-crumb"><a href="{{route('home')}}">Accueil</a><span>›</span><strong>{{$d['title']}}</strong></nav><section class="lp-hero lp-hero--{{$page}}"><div><h1>{{$d['title']}}</h1><p>{{$d['intro']}}</p>@if($page==='privacy')<span class="lp-date">Mise à jour : 28 août 2026</span>@endif</div></section><div class="lp-layout"><article class="lp-main">@if($page==='privacy')<section class="lp-intro"><h2>Notre engagement envers votre confidentialité</h2><p>Chez OVANIE, la confiance de nos utilisateurs, clients et partenaires est essentielle. Nous collectons uniquement les données nécessaires au bon fonctionnement de nos services.</p></section><div class="lp-features">@foreach([['database','Données collectées'],['crosshair','Utilisation des données'],['shield-check','Sécurité'],['user','Vos droits']] as $x)<div><i data-lucide="{{$x[0]}}"></i><strong>{{$x[1]}}</strong><span>Une gestion claire et responsable.</span></div>@endforeach</div>@endif<article class="lp-content">@foreach($d['sections'] as $n=>[$title,$text])<section id="section-{{$n+1}}" class="lp-section"><span class="lp-section__icon"><i data-lucide="{{['file-text','user-round','share-2','shield-check','mouse-pointer-2','user-check','archive','mail'][$n%8]}}"></i></span><div><h2>{{$n+1}}. {{$title}}</h2><p>{{$text}}</p>@if($page==='terms')<ul><li>Des informations fiables et à jour.</li><li>Une utilisation licite et respectueuse de la plateforme.</li></ul>@endif</div></section>@endforeach</article></article><aside><nav class="lp-side"><h3>Sommaire</h3>@foreach($d['sections'] as $n=>[$title,$text])<a href="#section-{{$n+1}}"><span>{{$n+1}}</span>{{$title}} <b>›</b></a>@endforeach</nav><div class="lp-note"><i data-lucide="{{$d['icon']}}"></i><h3>Vos droits, notre engagement</h3><p>Une expérience d’achat fiable, sécurisée et conforme.</p></div><div class="lp-help"><h3>Besoin d’aide ?</h3><p>Notre équipe répond à vos questions.</p><a class="ip-btn" href="{{route('contact.index')}}">Contacter OVANIE →</a></div></aside></div><section class="lp-trust"><h2>{{ $page==='terms' ? 'Achetez et utilisez OVANIE en toute confiance' : 'Une question sur vos données ? Contactez notre équipe' }}</h2><a class="ip-btn" href="{{route('contact.index')}}">Nous contacter →</a></section></div></main>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>window.lucide?.createIcons())</script>@endpush
