@extends('layouts.guest')
@php
$catalogUrl=route('catalog.index'); $contactUrl=Route::has('contact.index')?route('contact.index'):url('/contact');
$meta=['buy'=>['title'=>'Comment acheter sur OVANIE','crumb'=>'Comment acheter','heading'=>'Comment acheter<br>sur <em>OVANIE</em>','intro'=>'Un processus simple, rapide et sécurisé pour tous vos achats de matériaux et équipements BTP en ligne.','image'=>'comment-acheter.png'],'delivery'=>['title'=>'Livraison OVANIE','crumb'=>'Livraison','heading'=>'Livraison simple,<br>rapide et sécurisée<br>avec <em>OVANIE</em>','intro'=>'OVANIE organise votre livraison jusqu’à l’adresse de votre choix en Côte d’Ivoire.','image'=>'livraison.png'],'payment'=>['title'=>'Paiement sécurisé OVANIE','crumb'=>'Paiement sécurisé','heading'=>'Paiement sécurisé<br>à 100 % avec <em>OVANIE</em>','intro'=>'Vos paiements sont protégés à chaque étape. Choisissez le moyen qui vous convient et achetez en toute confiance.','image'=>'paiement.png'],'returns'=>['title'=>'Retours et remboursements OVANIE','crumb'=>'Retours et remboursements','heading'=>'Retours et<br>remboursements','intro'=>'Votre satisfaction est notre priorité. Si un produit présente un problème, nous sommes là pour vous aider.','image'=>'retours.png']]; $current=$meta[$page]??$meta['buy'];
$icons=['search'=>'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>','cart'=>'<path d="M3 4h2l2 10h11l2-7H6"/><circle cx="9" cy="19" r="1.5"/><circle cx="17" cy="19" r="1.5"/>','pin'=>'<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>','card'=>'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 9h18M7 15h5"/>','check'=>'<circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/>','truck'=>'<path d="M3 6h11v10H3zM14 10h4l3 3v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>','calculator'=>'<rect x="5" y="2" width="14" height="20" rx="2"/><path d="M8 6h8M8 11h1M12 11h1M16 11h1M8 15h1M12 15h1M16 15h1"/>','clock'=>'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>','box'=>'<path d="m12 3 8 4-8 4-8-4 8-4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/>','shield'=>'<path d="M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/>','return'=>'<path d="M9 7H4V2M4 7a9 9 0 1 1-1 8"/>','headset'=>'<path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v5H5a1 1 0 0 1-1-1v-4ZM20 14h-3v5h2a1 1 0 0 0 1-1v-4Z"/>','document'=>'<path d="M6 3h9l3 3v15H6zM15 3v4h4M9 11h6M9 15h6"/>','user'=>'<circle cx="12" cy="8" r="4"/><path d="M4 21c1-5 4-7 8-7s7 2 8 7"/>','quality'=>'<path d="m12 2 3 3 4 .5.5 4 2.5 2.5-2.5 3-.5 4-4 .5-3 3-3-3-4-.5-.5-4L2 12l2.5-3-.5-4L8 5z"/><path d="m8 12 2.5 2.5L16 9"/>','warning'=>'<path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5M12 18h.01"/>','money'=>'<ellipse cx="12" cy="6" rx="7" ry="3"/><path d="M5 6v6c0 1.7 3.1 3 7 3s7-1.3 7-3V6M5 12v6c0 1.7 3.1 3 7 3s7-1.3 7-3v-6"/>'];
$buySteps=[['search','Recherchez votre produit','Utilisez la recherche ou parcourez nos catégories.'],['cart','Ajoutez au panier','Sélectionnez la quantité et ajoutez le produit.'],['pin','Renseignez votre adresse','Indiquez l’adresse de livraison.'],['card','Choisissez votre paiement','Sélectionnez votre mode préféré.'],['check','Confirmez votre commande','Vérifiez les détails avant validation.'],['truck','Suivez la livraison','Suivez la commande jusqu’à réception.']];
$deliveryCards=[['calculator','Comment les frais sont calculés','Selon le poids, le volume, la nature des produits, la zone et le mode choisi.','Le montant exact est affiché avant validation.'],['pin','Zones desservies','Abidjan, ses communes, les grandes villes et les localités régionales éligibles.','La disponibilité est confirmée sur la fiche produit.'],['clock','Délais indicatifs','Abidjan : 24 à 72 h. Villes principales : 2 à 5 jours. Régions : 3 à 7 jours.','Les délais exacts sont indiqués à la commande.'],['truck','Livraison chantier','Accès camion, point précis et déchargement à l’endroit indiqué.','Préparez l’accès au chantier avant l’arrivée.'],['box','Poids et volume','Les produits lourds ou volumineux reçoivent une solution adaptée.','Dimensions et poids figurent sur la fiche produit.'],['document','Suivi de votre commande','Confirmation d’expédition, suivi des étapes et notification avant livraison.','Suivez votre commande depuis votre compte.']];
@endphp
@section('title',$current['title'])
@push('styles')<link rel="stylesheet" href="{{ asset('css/service-info.css') }}?v={{ filemtime(public_path('css/service-info.css')) }}">@endpush
@section('content')
<main class="osi osi-{{ $page }}"><div class="osi-wrap"><nav class="osi-crumb"><a href="{{ route('home') }}">Accueil</a><span>›</span><strong>{{ $current['crumb'] }}</strong></nav>
<header class="osi-hero" style="--hero:url('{{ asset('images/service-pages/'.$current['image']) }}')"><div class="osi-hero-copy"><h1>{!! $current['heading'] !!}</h1><p>{{ $current['intro'] }}</p><div class="osi-hero-points">@foreach(($page==='returns'?[['return','Simple et rapide'],['clock','Délais respectés'],['card','Remboursement'],['headset','Support dédié']]:[['shield','Simple'],['shield','Sécurisé'],['truck','Rapide'],['headset','Support 7j/7']]) as $point)<span><svg viewBox="0 0 24 24">{!! $icons[$point[0]] !!}</svg><b>{{ $point[1] }}</b></span>@endforeach</div></div></header>
@if($page==='buy')
<h2 class="osi-title">Votre parcours d’achat en 6 étapes</h2><section class="osi-flow six">@foreach($buySteps as $i=>$item)<article><i><svg viewBox="0 0 24 24">{!!$icons[$item[0]]!!}</svg></i><span>{{$i+1}}</span><b>{{$item[1]}}</b><p>{{$item[2]}}</p></article>@endforeach</section>
<section class="osi-panel"><h2>Pourquoi acheter sur OVANIE ?</h2><div class="osi-benefits">@foreach([['quality','Produits de qualité','Fournisseurs fiables'],['shield','Prix compétitifs','Toute l’année'],['card','Paiement sécurisé','Transactions protégées'],['truck','Livraison rapide','Partout en Côte d’Ivoire'],['user','Service dédié','Assistance 7j/7']] as $item)<div><i><svg viewBox="0 0 24 24">{!!$icons[$item[0]]!!}</svg></i><p><b>{{$item[1]}}</b><small>{{$item[2]}}</small></p></div>@endforeach</div></section>
<section class="osi-split"><div class="osi-panel"><h2>Modes de paiement acceptés</h2><div class="osi-mini">@foreach([['card','Mobile Money','Wave, Orange, MTN, Moov'],['card','Carte bancaire','Visa, Mastercard'],['money','Virement bancaire','Selon disponibilité'],['truck','Paiement à la livraison','Commandes éligibles']] as $item)<div><svg viewBox="0 0 24 24">{!!$icons[$item[0]]!!}</svg><b>{{$item[1]}}</b><small>{{$item[2]}}</small></div>@endforeach</div></div><div class="osi-panel osi-help"><svg viewBox="0 0 24 24">{!!$icons['headset']!!}</svg><div><h2>Besoin d’aide ?</h2><p>Notre équipe vous accompagne.</p><a href="{{$contactUrl}}">Nous contacter</a></div></div></section>
@elseif($page==='delivery')
<h2 class="osi-title">Tout ce qu’il faut savoir sur la livraison</h2><section class="osi-grid">@foreach($deliveryCards as $i=>$item)<article class="osi-card"><i><svg viewBox="0 0 24 24">{!!$icons[$item[0]]!!}</svg></i><h3>{{$i+1}}. {{$item[1]}}</h3><p>{{$item[2]}}</p><small>{{$item[3]}}</small></article>@endforeach</section><section class="osi-reception"><i><svg viewBox="0 0 24 24">{!!$icons['box']!!}</svg></i><div><h2>7. Réception de votre commande</h2><p>Vérifiez le nombre de colis et l’état de la marchandise en présence du livreur.</p></div><div><h3>En cas d’anomalie</h3><p>Notez vos réserves et contactez immédiatement le service client.</p></div></section>
@elseif($page==='payment')
<h2 class="osi-title">Des moyens de paiement adaptés à vos besoins</h2>@php $methods=[['wave','Wave','Payez facilement avec Wave.'],['orange','Orange Money','Réglez avec Orange Money.'],['mtn','MTN MoMo','Payez avec MTN Mobile Money.'],['moov','Moov Money','Utilisez votre compte Moov Money.']]; @endphp
<section class="osi-methods">@foreach($methods as $method)<article><img src="{{asset('images/operators/'.$method[0].'.png')}}" alt="{{$method[1]}}"><div><h3>{{$method[1]}}</h3><p>{{$method[2]}}</p><small>Rapide · Sécurisé</small></div></article>@endforeach<article><i><svg viewBox="0 0 24 24">{!!$icons['card']!!}</svg></i><div><h3>Carte bancaire</h3><p>Visa ou Mastercard si activée.</p><small>Sécurisé · International</small></div></article><article><i><svg viewBox="0 0 24 24">{!!$icons['box']!!}</svg></i><div><h3>Paiement à la livraison</h3><p>Pour les commandes éligibles.</p><small>Selon votre zone</small></div></article></section>
<section class="osi-security"><i><svg viewBox="0 0 24 24">{!!$icons['shield']!!}</svg></i><div><h3>Vos paiements sont entre de bonnes mains</h3><p>OVANIE ne stocke ni vos informations bancaires ni vos données de paiement. Les prestataires techniques traitent les opérations en arrière-plan.</p></div><b>Transactions chiffrées · Données protégées · Contrôles antifraude</b></section>
<section class="osi-panel"><h2 class="osi-title small">Comment ça fonctionne ?</h2><div class="osi-flow five">@foreach([['cart','Commandez'],['card','Choisissez'],['shield','Payez en sécurité'],['check','Confirmation'],['truck','Livraison']] as $i=>$item)<article><i><svg viewBox="0 0 24 24">{!!$icons[$item[0]]!!}</svg></i><span>{{$i+1}}</span><b>{{$item[1]}}</b></article>@endforeach</div></section>
@else
<section class="osi-panel concerned"><h2>Quels produits sont concernés ?</h2><div class="osi-benefits four">@foreach([['box','Produits éligibles','Non utilisés et complets'],['warning','Produits non éligibles','Ouverts ou installés'],['quality','Vérification','Contrôle à réception'],['document','Conditions spécifiques','Selon le type de produit']] as $item)<div><i><svg viewBox="0 0 24 24">{!!$icons[$item[0]]!!}</svg></i><p><b>{{$item[1]}}</b><small>{{$item[2]}}</small></p></div>@endforeach</div></section>
<section class="osi-panel"><h2>Dans quels cas puis-je retourner un produit ?</h2><div class="osi-reasons">@foreach([['truck','Produit endommagé','Défaut constaté à la réception.','48 h après réception'],['return','Mauvais produit reçu','Différent de celui commandé.','Signalez-le dès réception'],['box','Produit incomplet','Pièces ou accessoires manquants.','7 jours après réception'],['user','Changement d’avis','Produit neuf qui ne convient pas.','7 jours selon conditions']] as $item)<article><svg viewBox="0 0 24 24">{!!$icons[$item[0]]!!}</svg><h3>{{$item[1]}}</h3><p>{{$item[2]}}</p><small>{{$item[3]}}</small></article>@endforeach</div></section>
<section class="osi-panel"><h2>Comment effectuer un retour ?</h2><div class="osi-flow six compact">@foreach([['cart','Demande'],['card','Validation'],['shield','Préparation'],['headset','Expédition'],['truck','Vérification'],['money','Remboursement']] as $i=>$item)<article><i><svg viewBox="0 0 24 24">{!!$icons[$item[0]]!!}</svg></i><span>{{$i+1}}</span><b>{{$item[1]}}</b></article>@endforeach</div></section>
<section class="osi-split"><div class="osi-panel"><h2>Remboursement</h2><ul><li>Selon le mode de paiement utilisé.</li><li>Traitement après validation du retour.</li><li>Notification dès que le remboursement est effectué.</li><li>Frais initiaux non remboursés sauf erreur OVANIE.</li></ul></div><div class="osi-panel"><h2>Exceptions importantes</h2><ul><li>Produits en promotion, sauf défaut.</li><li>Produits scellés après ouverture.</li><li>Produits personnalisés ou sur mesure.</li><li>Cartes OVANIE non remboursables.</li></ul></div></section>
@endif
<section class="osi-cta"><div><h2>{{$page==='delivery'?'OVANIE s’occupe de tout.':($page==='returns'?'Besoin d’aide pour un retour ?':'Prêt à continuer vos achats ?')}}</h2><p>{{$page==='returns'?'Notre équipe est disponible pour vous accompagner.':'Commandez en confiance sur OVANIE.'}}</p></div><a href="{{$page==='returns'?$contactUrl:$catalogUrl}}">{{$page==='returns'?'Nous contacter':'Voir nos produits'}}</a></section>
</div></main>@endsection
