@extends('layouts.guest')
@section('title','Plan du site | OVANIE')
@section('styles')<link rel="stylesheet" href="{{asset('css/system-pages.css')}}">@endsection
@php
$groups=[
['home','Accueil',[['Page d’accueil',route('home')],['Promotions',route('catalog.index',['offer'=>'promotion'])],['Nouveautés',route('catalog.new-arrivals')],['Meilleures ventes',route('catalog.best-sellers')]]],
['layout-grid','Catégories',[['Matériaux gros œuvre',route('categories.show','materiaux-gros-oeuvre')],['Matériaux de finition',route('categories.show','materiaux-de-finition')],['Outillage & équipement',route('categories.show','outillage-equipement')],['Électricité & plomberie',route('categories.show','electricite-plomberie')],['Énergie solaire',route('categories.show','energie-solaire')],['Reconditionnés',route('categories.show','reconditionnes')]]],
['shopping-cart','Acheter',[['Catalogue produits',route('catalog.index')],['Comment acheter',route('how-to-buy')],['Paiement sécurisé',route('payment.secure')],['Livraison',route('delivery.info')],['Suivi de commande',route('order.tracking.public')]]],
['circle-user','Compte client',[['Mon profil',url('/profile')],['Mes commandes',url('/client/commandes')],['Mes favoris',url('/client/favoris')],['Mes cartes OVANIE',url('/client/cartes')]]],
['circle-help','Aide & Support',[['Centre d’aide',route('help.center')],['FAQ',route('faq')],['Contact',route('contact.index')],['Retours et remboursements',route('returns.refunds')],['Garantie acheteur',route('buyer.guarantee')],['Signaler un problème',route('problem.report')]]],
['store','Vendre sur OVANIE',[['Pourquoi vendre sur OVANIE ?',route('sell.on.ovanie')],['Ouvrir ma boutique',route('open-shop')],['Conditions vendeurs',route('vendor.terms')]]],
['handshake','Partenaires',[['Partenaires / Fournisseurs',route('partners.suppliers')],['Devenir partenaire',route('partners.suppliers').'#contact']]],
['gift','Cartes OVANIE',[['Découvrir les cartes',route('gift-cards.index')],['Comment ça marche ?',route('gift-cards.how-it-works')],['Conditions d’utilisation',route('gift-cards.terms')]]],
['building-2','À propos',[['Qui sommes-nous ?',route('about')],['Notre mission',route('company.mission')],['Nos valeurs',route('company.values')],['Carrières',route('careers')],['Nous contacter',route('contact.index')]]]
];
@endphp
@section('content')<main class="sm-page"><div class="sys-shell"><nav class="sys-crumb"><a href="{{route('home')}}">Accueil</a><span>›</span><strong>Plan du site</strong></nav><section class="sm-hero"><div><h1>Plan du site</h1><p>Retrouvez facilement toutes les pages et informations disponibles sur OVANIE.</p><p>Utilisez ce plan pour naviguer rapidement vers la section qui vous intéresse.</p></div><div class="sm-tree"><b>OVANIE</b><span></span><div>@foreach(['home','layout-grid','shopping-cart','user','circle-help'] as $i)<i data-lucide="{{$i}}"></i>@endforeach</div></div></section><h2 class="sys-title">Explorer OVANIE</h2><section class="sm-grid">@foreach($groups as [$icon,$title,$links])<article><span><i data-lucide="{{$icon}}"></i></span><h3>{{$title}}</h3>@foreach($links as [$label,$href])<a href="{{$href}}">{{$label}}</a>@endforeach</article>@endforeach</section><h2 class="sys-title">Informations légales & sécurité</h2><div class="sm-legal"><a href="{{route('terms')}}"><i data-lucide="file-check"></i>Conditions générales d’utilisation</a><a href="{{route('privacy-policy')}}"><i data-lucide="lock"></i>Politique de confidentialité</a><a href="{{route('legal.notice')}}"><i data-lucide="landmark"></i>Mentions légales</a></div><section class="sys-help"><i data-lucide="headphones"></i><div><h2>Besoin d’aide ?</h2><p>Notre équipe est disponible pour vous accompagner.</p></div><a href="{{route('contact.index')}}">Nous contacter</a><a class="primary" href="{{route('help.center')}}">Centre d’aide</a></section></div></main>@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>window.lucide?.createIcons())</script>@endpush
