<?php
namespace App\Http\Controllers\Api\Commercial;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Shop;
use App\Services\OvanieReferenceDataService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class CommercialMobileProductController extends Controller {
 private function shops(Request $r){$id=(int)$r->user()->id;return Shop::query()->where(function($q)use($id){$q->where('created_by_commercial_id',$id)->orWhere('managed_by_commercial_id',$id);});}
 private function ownShop(Request $r,int $id): Shop {return $this->shops($r)->findOrFail($id);}
 public function shopsIndex(Request $r): JsonResponse { $q=trim((string)$r->query('q','')); $rows=$this->shops($r)->withCount('products')->when($q!=='',fn($x)=>$x->where('name','like',"%$q%"))->latest()->get(); return response()->json(['shops'=>$rows->map(fn($s)=>['id'=>$s->id,'name'=>$s->name,'category'=>$s->main_category?:'Boutique OVANIE','location'=>trim(($s->city?:'').' '.($s->commune?:''), ' ,'),'products_count'=>(int)$s->products_count,'status'=>$s->status==='suspended'?'suspended':($s->status==='approved' || $s->is_active?'online':'pending'),'logistics'=>($s->logistics_type??'ovanie')==='seller'?'Logistique vendeur':'OVANIE Logistics','image_url'=>$s->logo_url??null])->values()]); }
 public function meta(OvanieReferenceDataService $references): JsonResponse { $categories=collect($references->productCategories())->map(fn($c)=>['id'=>$c['id'],'name'=>$c['name'],'children'=>collect($c['children']??[])->map(fn($x)=>['id'=>$x['id'],'name'=>$x['name']])->values()])->values(); return response()->json(['categories'=>$categories,'units'=>$references->codes('product_units')]); }
 public function sessions(Request $r): JsonResponse { $shop=$this->ownShop($r,(int)$r->query('shop_id')); $rows=DB::table('commercial_capture_sessions')->where('commercial_id',$r->user()->id)->where('shop_id',$shop->id)->latest()->get(); return response()->json(['sessions'=>$rows->map(fn($s)=>$this->sessionPayload($s,$shop))->values()]); }
 public function createSession(Request $r): JsonResponse { $d=$r->validate(['shop_id'=>'required|integer','name'=>'required|string|max:150','category_id'=>'required|integer|exists:categories,id','subcategory_id'=>'nullable|integer|exists:categories,id','notes'=>'nullable|string|max:1000','keep_category'=>'boolean']); $shop=$this->ownShop($r,(int)$d['shop_id']); $id=DB::table('commercial_capture_sessions')->insertGetId(['commercial_id'=>$r->user()->id,'shop_id'=>$shop->id,'name'=>$d['name'],'category_id'=>$d['category_id'],'subcategory_id'=>$d['subcategory_id']??null,'notes'=>$d['notes']??null,'keep_category'=>$d['keep_category']??true,'status'=>'in_progress','created_at'=>now(),'updated_at'=>now()]); return response()->json(['session'=>$this->sessionPayload(DB::table('commercial_capture_sessions')->find($id),$shop)],201); }
 public function session(Request $r,int $id): JsonResponse { $s=$this->ownedSession($r,$id); $shop=$this->ownShop($r,(int)$s->shop_id); $products=$this->sessionProducts($s->id); return response()->json(['session'=>$this->sessionPayload($s,$shop),'products'=>$products->map(fn($p)=>$this->productPayload($p))->values()]); }
 public function capture(Request $r): JsonResponse { $d=$r->validate(['session_id'=>'required|integer','category_id'=>'required|integer|exists:categories,id','subcategory_id'=>'nullable|integer|exists:categories,id','photo'=>'required|image|mimes:jpg,jpeg,png,webp|max:8192']); $s=$this->ownedSession($r,(int)$d['session_id']); $shop=$this->ownShop($r,(int)$s->shop_id); $categoryId=(int)($d['subcategory_id']??$d['category_id']); $path=$r->file('photo')->store('products/commercial-capture','public'); $p=DB::transaction(function() use ($r,$d,$s,$shop,$categoryId,$path) { $n=DB::table('commercial_capture_session_products')->where('session_id',$s->id)->count()+1; $attrs=['commercial_capture'=>true,'capture_session_id'=>$s->id,'main_category_id'=>(int)$d['category_id'],'subcategory_id'=>$d['subcategory_id']??null,'completion_step'=>0]; $vals=['shop_id'=>$shop->id,'category_id'=>$categoryId,'name'=>'Produit capturé #'.$n,'slug'=>Str::slug($shop->name.' produit '.$n.' '.Str::random(5)),'description'=>null,'price'=>0,'stock'=>0,'is_active'=>false]; if(Schema::hasColumn('products','created_by_commercial_id'))$vals['created_by_commercial_id']=$r->user()->id; if(Schema::hasColumn('products','status'))$vals['status']='draft'; if(Schema::hasColumn('products','product_attributes'))$vals['product_attributes']=$attrs; $p=Product::create($vals); $imgVals=['product_id'=>$p->id,'path'=>$path,'is_main'=>true,'is_primary'=>true]; if(Schema::hasColumn('product_images','image_path'))$imgVals['image_path']=$path; ProductImage::create($imgVals); DB::table('commercial_capture_session_products')->insert(['session_id'=>$s->id,'product_id'=>$p->id,'capture_status'=>'draft','created_at'=>now(),'updated_at'=>now()]); return $p; }); $p->load(['category','images']); return response()->json(['product'=>$this->productPayload($p)],201); }
 public function finish(Request $r,int $id): JsonResponse { $s=$this->ownedSession($r,$id); DB::table('commercial_capture_sessions')->where('id',$s->id)->update(['status'=>'finished','finished_at'=>now(),'updated_at'=>now()]); return response()->json(['ok'=>true]); }
 public function incomplete(Request $r): JsonResponse { $s=$this->ownedSession($r,(int)$r->query('session_id')); $ps=$this->sessionProducts($s->id)->filter(fn($p)=>!$p->is_active); return response()->json(['products'=>$ps->map(fn($p)=>$this->productPayload($p))->values()]); }
 public function edit(Request $r,Product $product): JsonResponse { $this->assertProduct($r,$product); $product->load(['category.parent','images']); return response()->json(['product'=>$this->productPayload($product,true)]); }
 public function saveStep(Request $r,Product $product,int $step): JsonResponse { $this->assertProduct($r,$product); abort_unless($step>=1&&$step<=5,404); $a=(array)($product->product_attributes??[]); foreach($r->all() as $k=>$v){if($v!==null)$a[$k]=$v;} $map=[];
  if($step===1){foreach(['name','brand','short_description','description'] as $k) if(isset($a[$k])&&Schema::hasColumn('products',$k))$map[$k]=$a[$k]; if(isset($a['name'])){$map['name']=$a['name'];$map['slug']=Str::slug($a['name'].'-'.$product->id);} }
  if($step===2){foreach(['price','promo_price','stock','unit','unit_label','min_order_quantity','sale_type'] as $k) if(isset($a[$k])&&Schema::hasColumn('products',$k)){ $value=$a[$k]===''?null:$a[$k]; if(in_array($k,['price','promo_price'],true)&&$value!==null){$value=max(0,(int)round((float)str_replace(',','.',(string)$value)));} $map[$k]=$value; }}
  if($step===3){foreach(['usage_area','technical_details','warranty'] as $k) if(isset($a[$k])&&Schema::hasColumn('products',$k))$map[$k]=$a[$k]===''?null:$a[$k];}
  if($step===4){foreach(['weight_kg','length_cm','width_cm','height_cm'] as $k) if(isset($a[$k])&&Schema::hasColumn('products',$k))$map[$k]=$a[$k]===''?null:$a[$k]; if(isset($a['fragile'])&&Schema::hasColumn('products','fragile'))$map['fragile']=filter_var($a['fragile'],FILTER_VALIDATE_BOOLEAN); if(isset($a['requires_unloading'])&&Schema::hasColumn('products','requires_unloading'))$map['requires_unloading']=filter_var($a['requires_unloading'],FILTER_VALIDATE_BOOLEAN); if(isset($a['unloading_instructions'])&&Schema::hasColumn('products','unloading_instructions'))$map['unloading_instructions']=$a['unloading_instructions'];}
  $a['completion_step']=max((int)($a['completion_step']??0),$step); if(Schema::hasColumn('products','product_attributes'))$map['product_attributes']=$a; $product->update($map); return response()->json(['ok'=>true,'product'=>$this->productPayload($product->fresh(['category','images']),true)]); }
 public function media(Request $r,Product $product): JsonResponse { $this->assertProduct($r,$product); $d=$r->validate(['kind'=>'nullable|string|max:20','media'=>'required|file|max:20480']); $path=$r->file('media')->store('products/commercial-media','public'); $imgVals=['product_id'=>$product->id,'path'=>$path,'is_main'=>$product->images()->count()===0,'is_primary'=>$product->images()->count()===0]; if(Schema::hasColumn('product_images','image_path'))$imgVals['image_path']=$path; ProductImage::create($imgVals); return response()->json(['ok'=>true,'url'=>Storage::url($path)]); }
 public function publish(Request $r,Product $product): JsonResponse { $this->assertProduct($r,$product); $a=(array)($product->product_attributes??[]); if((float)$product->price<=0 || (int)$product->stock<0 || empty($product->name) || $product->images()->count()===0) return response()->json(['message'=>'La fiche produit est incomplète : nom, prix et photo sont obligatoires.'],422); $product->update(array_filter(['is_active'=>true,'status'=>Schema::hasColumn('products','status')?'active':null],fn($v)=>$v!==null)); DB::table('commercial_capture_session_products')->where('product_id',$product->id)->update(['capture_status'=>'completed','updated_at'=>now()]); return response()->json(['ok'=>true,'product'=>$this->productPayload($product->fresh(['category','images']),true)]); }
 private function ownedSession(Request $r,int $id){$s=DB::table('commercial_capture_sessions')->where('id',$id)->where('commercial_id',$r->user()->id)->first();abort_unless($s,404);return $s;}
 private function sessionProducts(int $sid){$ids=DB::table('commercial_capture_session_products')->where('session_id',$sid)->pluck('product_id');return Product::query()->whereIn('id',$ids)->with(['category.parent','images'])->orderBy('id')->get();}
 private function assertProduct(Request $r,Product $p): void {$shop=$this->ownShop($r,(int)$p->shop_id); abort_unless($shop->id===$p->shop_id,404);}
 private function sessionPayload($s,Shop $shop): array {$ids=DB::table('commercial_capture_session_products')->where('session_id',$s->id)->pluck('product_id');$captured=$ids->count();$completed=$ids->isEmpty()?0:Product::whereIn('id',$ids)->where('is_active',true)->count();$cat=$s->category_id?Category::find($s->category_id):null;$sub=$s->subcategory_id?Category::find($s->subcategory_id):null;return ['id'=>$s->id,'shop_id'=>$shop->id,'shop_name'=>$shop->name,'name'=>$s->name,'status'=>$s->status,'captured'=>$captured,'completed'=>$completed,'drafts'=>max(0,$captured-$completed),'sync_status'=>'synced','date'=>optional($s->created_at?\Carbon\Carbon::parse($s->created_at):now())->format('d/m/Y H:i'),'category_id'=>$s->category_id,'category'=>$cat?->name??'','subcategory_id'=>$s->subcategory_id,'subcategory'=>$sub?->name??''];}
 private function productPayload(Product $p,bool $full=false): array {$p->loadMissing(['category.parent','images']);$a=(array)($p->product_attributes??[]);$main=$p->category?->parent?:$p->category;$sub=$p->category?->parent?$p->category:null;$base=['id'=>$p->id,'name'=>$p->name,'reference'=>$p->sku?:('PRD-'.str_pad((string)$p->id,4,'0',STR_PAD_LEFT)),'status'=>$p->is_active?'completed':'draft','image_url'=>$p->images->first()?->public_url??'','category'=>$main?->name??'','subcategory'=>$sub?->name??'','captured_at'=>optional($p->created_at)->format('H:i'),'attributes'=>$a]; if(!$full)return $base; return array_merge($base,$a,['brand'=>$p->brand,'short_description'=>$p->short_description,'description'=>$p->description,'price'=>$p->price,'promo_price'=>$p->promo_price,'stock'=>$p->stock,'unit'=>$p->unit,'unit_label'=>$p->unit_label,'min_order_quantity'=>$p->min_order_quantity,'sale_type'=>$p->sale_type,'content_per_unit'=>$p->content_per_unit,'color'=>$p->color,'standard'=>$p->standard,'usage_area'=>$p->usage_area,'technical_details'=>$p->technical_details,'warranty'=>$p->warranty,'packaging'=>$p->packaging,'weight_kg'=>$p->weight_kg,'length_cm'=>$p->length_cm,'width_cm'=>$p->width_cm,'height_cm'=>$p->height_cm,'fragile'=>(bool)$p->fragile,'requires_unloading'=>(bool)$p->requires_unloading,'unloading_instructions'=>$p->unloading_instructions]);}
}
