<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Répertoire opérationnel des localités du District autonome d’Abidjan
    |--------------------------------------------------------------------------
    |
    | Le catalogue améliore l’autocomplétion et la normalisation GPS. Il ne
    | constitue jamais une liste fermée de desserte : la commune reconnue reste
    | la règle d’éligibilité et un quartier absent du catalogue n’est pas refusé.
    |
    */
    'district' => 'District autonome d’Abidjan',
    'country_code' => 'CI',
    'generic_aliases' => [
        'Abidjan',
        'District autonome d’Abidjan',
        'District d’Abidjan',
        'Abidjan Autonomous District',
    ],
    'communes' => [
        'Abobo' => [
            'code' => 'ABO',
            'aliases' => ['Abobo'],
            'quarters' => [
                'Abobo Centre',
                'Abobo Gare',
                'Abobo Baoulé',
                'Abobo Té',
                'Abobo Clouetcha',
                'Abobo Belleville',
                'Abobo Habitat',
                'Abobo Kennedy',
                'Abobo Banco',
                'Abobo Plaque 1',
                'Abobo Plaque 2',
                'Abobo Sagbé',
                'Avocatier',
                ['name' => 'PK 18', 'aliases' => ['PK18', 'PK-18']],
                ['name' => 'N\'Dotré', 'aliases' => ['Ndotré', 'N Dotre', 'N\'Dotre']],
                ['name' => 'Anonkoa Kouté', 'aliases' => ['Anonkoa Koute', 'Anonkoua Kouté', 'Anonkoua Koute']],
                'Samaké',
                'Agnissankoi',
                'Akeikoi',
                'Biabou',
                'Akéikoi Extension',
                'Dokui Extension',
                'Derrière Rails',
                'Sogefiha',
                'Sicogi',
                'Houphouët-Boigny',
                'Abobo Nord',
                'Abobo Sud',
                'Abobo Est',
                'Abobo Ouest',
                'Cité de la Paix',
                'Cité policière',
                'Camp Commando',
            ],
        ],
        'Adjamé' => [
            'code' => 'ADJ',
            'aliases' => ['Adjame'],
            'quarters' => [
                'Mairie I',
                'Mairie II',
                'Bromakoté',
                'Adjamé Nord',
                ['name' => '220 Logements', 'aliases' => ['220 logements', 'Deux cent vingt logements']],
                'Habitat Extension',
                'Paillet',
                'Marie-Thérèse',
                'Saint-Michel',
                'Village Ébrié',
                'Dallas',
                'Indénié',
                'Williamsville I',
                'Williamsville II',
                'Williamsville III',
                'SODECI-FILTISAC',
                'Mirador',
                'Adjamé Nord-Est',
                'Quartier Ébrié',
                'Liberté',
                'Agban Gendarmerie',
                'Bracodi',
                'Fraternité-Matin',
                'Forum des Marchés',
            ],
        ],
        'Anyama' => [
            'code' => 'ANY',
            'aliases' => ['Anyama', 'Ayama'],
            'quarters' => [
                'Anyama Centre',
                'Anyama Gare',
                'Anyama Résidentiel',
                'Anyama Adjamé',
                'Anyama Ahouabo',
                'Ebimpé',
                'Attingué',
                ['name' => 'Akoupé-Zeudji', 'aliases' => ['Akoupe Zeudji']],
                'Allokoi',
                'Adonkoi',
                'Thomasset',
                'Broutoi',
                'Belleville Anyama',
                'Schneider',
                'RAN',
                'CEG',
                'Zossonkoi',
                'Azaguié-Blida',
                'Ahoué',
                'Akéikoi Anyama',
            ],
        ],
        'Attécoubé' => [
            'code' => 'ATT',
            'aliases' => ['Attecoube', 'Attecoubet'],
            'quarters' => [
                ['name' => 'Attécoubé Centre', 'aliases' => ['Attecoube Centre']],
                'Attécoubé 3',
                ['name' => 'Abobodoumé', 'aliases' => ['Abobodoume']],
                'Agban Village',
                'Boribana',
                'Locodjro',
                'Mossikro',
                'Santé 3',
                'Sebroko',
                'Banco Attécoubé',
                'Jean-Paul II',
                'Lackman',
                'Djéné Ecarrefour',
                'Abidjan Santé',
                'Résidentiel Attécoubé',
                'Camp Douane',
                'Gbêkê',
                'Espoir',
                'Fromager',
            ],
        ],
        'Bingerville' => [
            'code' => 'BIN',
            'aliases' => ['Bingerville'],
            'quarters' => [
                'Bingerville Centre',
                'Bingerville Gare',
                'Bingerville Résidentiel',
                'SICOGI Bingerville',
                'Adjamé-Bingerville',
                ['name' => 'Akandjé', 'aliases' => ['Akandje']],
                ['name' => 'Feh Kessé', 'aliases' => ['Feh Kesse']],
                'Elokaté',
                'Elokato',
                'Anan',
                ['name' => 'Akoué-Santé', 'aliases' => ['Akoue Sante']],
                'Brégbo',
                'Achokoi',
                'Abatta',
                'M\'Badon Extension',
                'Santé Bingerville',
                'Palmeraie Bingerville',
                'Cité Marina',
                'Cité Feh Kessé',
                'Carrefour M\'Batto-Bouaké',
                'Koffikro',
                'Ana',
                'Akouai-Agban',
            ],
        ],
        'Cocody' => [
            'code' => 'COC',
            'aliases' => ['Cocody'],
            'quarters' => [
                'Cocody Centre',
                'Cocody Danga',
                'Cocody Ambassades',
                'Cocody Saint-Jean',
                'Cocody Lycée Technique',
                'Cocody Mermoz',
                'Cocody Cité des Arts',
                'Cocody Cité SIR',
                'Cocody Blockhauss',
                'Cocody Golf',
                ['name' => 'Deux-Plateaux', 'aliases' => ['Deux Plateaux', '2 Plateaux', 'Les Deux Plateaux']],
                'Deux-Plateaux Vallon',
                'Deux-Plateaux Aghien',
                'Deux-Plateaux Dokui',
                'Deux-Plateaux ENA',
                'Deux-Plateaux Les Perles',
                'Deux-Plateaux Mobile',
                'Deux-Plateaux 7e Tranche',
                ['name' => 'Angré', 'aliases' => ['Angre']],
                'Angré 7e Tranche',
                'Angré 8e Tranche',
                'Angré 9e Tranche',
                'Angré Château',
                'Angré Nouveau CHU',
                'Riviera 1',
                'Riviera 2',
                'Riviera 3',
                'Riviera 4',
                'Riviera 5',
                'Riviera 6',
                'Riviera Golf',
                ['name' => 'Riviera Palmeraie', 'aliases' => ['Palmeraie']],
                'Riviera Bonoumin',
                'Riviera Faya',
                'Riviera Attoban',
                'Riviera M\'Badon',
                'Bonoumin',
                'Faya',
                'Attoban',
                'Anono',
                ['name' => 'Akouédo', 'aliases' => ['Akouedo']],
                ['name' => 'Djorogobité 1', 'aliases' => ['Djorogobite 1']],
                ['name' => 'Djorogobité 2', 'aliases' => ['Djorogobite 2']],
                ['name' => 'M\'Pouto', 'aliases' => ['Mpouto', 'M Pouto']],
                ['name' => 'Cité ATCI', 'aliases' => ['Cite ATCI', 'ATCI']],
                'Génie 2000',
                'Abatta Cocody',
                'Bessikoi',
                'Lauriers',
                'Rosiers Programme 1',
                'Rosiers Programme 2',
                'Rosiers Programme 3',
                'Rosiers Programme 4',
                'Sopim',
                'Sicogi Latrille',
                'Cité Allabra',
                'Cité Synacass-CI',
                'Cité BCEAO',
                'Cité BAD',
                'Cité EECI',
                'Cité des Cadres',
                'Washington',
                'Val Doyen',
                'Cité Lemania',
            ],
        ],
        'Koumassi' => [
            'code' => 'KOU',
            'aliases' => ['Koumassi'],
            'quarters' => [
                'Koumassi Centre',
                'Koumassi Nord',
                'Koumassi Nord-Est',
                'Koumassi Sud',
                ['name' => 'Koumassi Remblais', 'aliases' => ['Remblais Koumassi']],
                'Grand Campement',
                'Divo 1',
                'Divo 2',
                'Akromiabla',
                'Prodomo',
                'Campement',
                'SICOGI Koumassi',
                'SOGEFIHA Koumassi',
                'Zone Industrielle Koumassi',
                'Pangolin',
                'Sopim Koumassi',
                'Quartier 05',
                'Quartier 14',
                'Quartier 32',
                'Quartier 36',
                'Quartier 38',
                'Quartier 41',
                'Quartier 45',
                'Cité Houphouët-Boigny',
                'Cité Addoha Koumassi',
                'Carrefour Akwaba Koumassi',
                'Bia Sud',
            ],
        ],
        'Marcory' => [
            'code' => 'MAR',
            'aliases' => ['Marcory'],
            'quarters' => [
                'Marcory Centre',
                'Marcory Résidentiel',
                ['name' => 'Marcory Zone 4', 'aliases' => ['Zone 4', 'Zone quatre']],
                'Zone 4 C',
                ['name' => 'Zone 4 Biétry', 'aliases' => ['Zone 4 Bietry', 'Bietry Zone 4']],
                ['name' => 'Biétry', 'aliases' => ['Bietry']],
                'Marcory Zone 3',
                ['name' => 'Anoumabo', 'aliases' => ['Anoumanbo']],
                'Hibiscus',
                'Champroux',
                'GFCI',
                'Aliodan',
                'Sans Fil',
                'SICOGI Marcory',
                'Konan Raphaël',
                'Poto-Poto',
                'Remblais Marcory',
                'Cité Hibiscus',
                'Cité Presse',
                'Cité Marie-Koré',
                'Petit Bouaké',
                'Grand Carrefour Marcory',
                'Résidentiel 7 Hectares',
                'Ancien Koumassi',
            ],
        ],
        'Plateau' => [
            'code' => 'PLA',
            'aliases' => ['Plateau', 'Le Plateau'],
            'quarters' => [
                'Plateau Centre',
                'Cité Administrative',
                'Quartier Commerce',
                'Quartier des Affaires',
                'Indénié Plateau',
                'Carena',
                'Plateau Dokui administratif',
                'Résidentiel Plateau',
                'Jardin Public',
                'Cité Esculape',
                'Zone Portuaire Plateau',
                'Avenue Chardy',
                'Avenue Franchet-d\'Esperey',
                'Boulevard de la République',
            ],
        ],
        'Port-Bouët' => [
            'code' => 'PBO',
            'aliases' => ['Port Bouët', 'Port-Bouet', 'Port Bouet'],
            'quarters' => [
                'Port-Bouët Centre',
                'Vridi',
                'Vridi Canal',
                'Vridi Cité',
                'Vridi 3',
                'Vridi Zone Industrielle',
                'Gonzagueville',
                'Adjouffou',
                'Jean-Folly',
                ['name' => 'Derrière Wharf', 'aliases' => ['Derriere Wharf']],
                'Aéroport',
                'Akwaba',
                'Petit-Bassam',
                'Abia',
                'Anani',
                'Modeste',
                'Maffiblé',
                'Abouabou',
                'SOGEFIHA Port-Bouët',
                'SICOGI Port-Bouët',
                'Ancien Koumassi Port-Bouët',
                'Cité de l\'Air',
                'Cité policière Port-Bouët',
                'Camp Gendarmerie',
                'Rue des Pêcheurs',
                'Phare de Port-Bouët',
                'Bassam 1',
                'Bassam 2',
            ],
        ],
        'Songon' => [
            'code' => 'SON',
            'aliases' => ['Songon'],
            'quarters' => [
                ['name' => 'Songon Kassemblé', 'aliases' => ['Songon Kassemble']],
                ['name' => 'Songon Dagbé', 'aliases' => ['Songon Dagbe']],
                'Songon Agban',
                ['name' => 'Songon M\'Brathé', 'aliases' => ['Songon Mbrathe', 'Songon M Brathe']],
                'Songon Té',
                'Songon Centre',
                'Nonkouagon',
                'Bago',
                'Adiapoto',
                'Kossihouen',
                'Abadjin-Kouté',
                'Abadjin-Doumé',
                'Abadjin-Brimbresso',
                'Adiopodoumé',
                'Bimbresso',
                'Songon M\'Brathé Résidentiel',
                'Songon Extension',
                'Songon Terminal',
                'Niangon-Adjamé',
                'Kassemblé Village',
            ],
        ],
        'Treichville' => [
            'code' => 'TRE',
            'aliases' => ['Treichville'],
            'quarters' => [
                'Treichville Centre',
                'Arras 1',
                'Arras 2',
                'Arras 3',
                'Arras 4',
                'Biafra',
                'Belleville Treichville',
                'Habitat Treichville',
                'France-Amérique',
                'Gbatanikro',
                'Apollo',
                'SICOGI Treichville',
                'SOGEFIHA Treichville',
                'Zone Portuaire Treichville',
                'Canal aux Bois',
                'Avenue 8',
                'Avenue 16',
                'Avenue 21',
                'Avenue 24',
                'Marché de Treichville',
                'Palais des Sports',
                'Cité Douane',
            ],
        ],
        'Yopougon' => [
            'code' => 'YOP',
            'aliases' => ['Yopougon'],
            'quarters' => [
                'Yopougon Centre',
                'Yopougon Gare',
                'Yopougon Santé',
                'Yopougon Attié',
                'Yopougon Kouté',
                'Niangon Nord',
                'Niangon Sud',
                ['name' => 'Niangon à Gauche', 'aliases' => ['Niangon a Gauche']],
                ['name' => 'Niangon à Droite', 'aliases' => ['Niangon a Droite']],
                'Siporex',
                'Selmer',
                'Wassakara',
                'Toits Rouges',
                'Gesco',
                'Maroc',
                'Maroc Antenne',
                'SICOGI Yopougon',
                'SOGEFIHA Yopougon',
                'SIDEci',
                'Andokoi',
                'Azito',
                'Académie',
                'Banco Yopougon',
                'Port-Bouët 2',
                'Nouveau Quartier',
                'Millionnaire',
                'MICAO',
                'Lokoa',
                ['name' => 'Koweït', 'aliases' => ['Koweit']],
                'Camp Militaire',
                'Ananeraie',
                'Terminus 27',
                'Lubafrique',
                'Cité Verte',
                'Sable',
                'Kouté Village',
                'Azito Village',
                'Abobodoumé Yopougon',
                ['name' => 'Yaosséhi', 'aliases' => ['Yaossehi']],
                ['name' => 'Mami-Faitai', 'aliases' => ['Mamie Faitai']],
                'Camp Manguier',
                'Camp Militaire 1',
                'Camp Militaire 2',
                'Cité CIE',
                'Cité SIR',
                'Cité GFCI',
                'Sideci Lem',
                'Sideci Terminus',
                'Sicogi 1',
                'Sicogi 2',
                'Sicogi 3',
                'Sicogi 4',
                'Sicogi 5',
                'Selmer Camp',
                'Selmer Mairie',
                'Wassakara Carrefour',
                'Niangon Lokoa',
                'Niangon Cité Verte',
                'Niangon Lubafrique',
                'Niangon Adjamé',
                'Bonikro',
                'Kossihouen Yopougon',
                'N\'Dotré Yopougon',
                'Mahou',
                'Kouté Extension',
                'Yopougon Industriel',
                'Zone Industrielle Yopougon',
                'Cité Coprim',
                'Cité Bel Air',
                'Cité Nawa',
                'Cité Sopim',
                'Cité Addoha Yopougon',
                'Cité ADO',
                'Cité Mamie Adjoua',
            ],
        ],
    ],
];
