<?php

return [
    'internal_roles' => ['admin', 'logistique', 'support', 'commercial'],
    'managed_roles' => ['logistique', 'support', 'commercial'],

    'permissions' => [
        'tickets.read' => 'Consulter les tickets et dossiers Support',
        'tickets.write' => 'Créer, attribuer et traiter les tickets',
        'messages.read' => 'Consulter les messages publics entrants',
        'customers.read' => 'Consulter les clients',
        'customers.write' => 'Créer des comptes clients',
        'vendors.read' => 'Consulter les vendeurs et boutiques',
        'vendors.write' => 'Créer et attribuer des vendeurs et boutiques',
        'orders.read' => 'Consulter les commandes',
        'payments.read' => 'Consulter les paiements',
        'deliveries.read' => 'Consulter les livraisons et incidents',
        'returns.read' => 'Consulter les retours et remboursements',
        'disputes.read' => 'Consulter les litiges',
        'leads.read' => 'Consulter le pipeline commercial',
        'leads.write' => 'Créer et mettre à jour les opportunités',
        'products.read' => 'Consulter le catalogue produits',
        'products.write' => 'Créer et publier des produits pour les vendeurs attribués',
        'quotes.read' => 'Consulter les demandes OVANIE Pro, devis et appels d’offres',

        'support.ai.agents.read' => 'Consulter les agents IA du Support',
        'support.ai.agents.manage' => 'Activer, suspendre et configurer les agents IA',
        'support.ai.conversations.read' => 'Consulter les conversations IA',
        'support.ai.conversations.respond' => 'Répondre dans les conversations et déclencher une réponse IA',
        'support.ai.conversations.takeover' => 'Prendre en charge et transférer les conversations',
        'support.ai.calls.read' => 'Consulter les appels et leurs transcriptions',
        'support.ai.calls.initiate' => 'Lancer des appels sortants et créer des rappels',
        'support.ai.calls.transfer' => 'Transférer les appels vers un agent humain',
        'support.ai.handoffs.read' => 'Consulter les transferts humains',
        'support.ai.handoffs.manage' => 'Accepter et clôturer les transferts humains',
        'support.ai.callbacks.read' => 'Consulter les demandes de rappel',
        'support.ai.callbacks.manage' => 'Planifier et clôturer les demandes de rappel',
        'support.ai.knowledge.read' => 'Consulter la base de connaissances IA',
        'support.ai.knowledge.manage' => 'Créer et publier les connaissances utilisées par l’IA',
        'support.ai.supervision' => 'Superviser les décisions, tickets et escalades IA',

        'logistics.dashboard.read' => 'Consulter le tableau de bord logistique',
        'logistics.shipments.read' => 'Consulter les expéditions',
        'logistics.shipments.write' => 'Affecter et mettre à jour les expéditions',
        'logistics.tracking.read' => 'Consulter le suivi et les positions de livraison',
        'logistics.incidents.read' => 'Consulter les incidents logistiques',
        'logistics.incidents.write' => 'Créer et traiter les incidents logistiques',
        'logistics.drivers.read' => 'Consulter les livreurs et leurs accès',
        'logistics.drivers.write' => 'Créer et modifier les livreurs et leurs accès',
        'logistics.returns.read' => 'Consulter les retours logistiques',
        'logistics.returns.write' => 'Approuver ou rejeter les retours logistiques',
        'logistics.zones.read' => 'Consulter les zones de livraison',
        'logistics.zones.write' => 'Créer et modifier les zones de livraison',
        'logistics.pricing.read' => 'Consulter la tarification OVANIE Logistics',
        'logistics.pricing.write' => 'Modifier la tarification OVANIE Logistics',
    ],

    'role_permissions' => [
        'support' => [
            'tickets.read', 'tickets.write', 'messages.read', 'customers.read', 'vendors.read',
            'orders.read', 'payments.read', 'deliveries.read', 'returns.read', 'disputes.read',
            'support.ai.agents.read', 'support.ai.agents.manage',
            'support.ai.conversations.read', 'support.ai.conversations.respond', 'support.ai.conversations.takeover',
            'support.ai.calls.read', 'support.ai.calls.initiate', 'support.ai.calls.transfer',
            'support.ai.handoffs.read', 'support.ai.handoffs.manage',
            'support.ai.callbacks.read', 'support.ai.callbacks.manage',
            'support.ai.knowledge.read', 'support.ai.knowledge.manage', 'support.ai.supervision',
        ],
        'commercial' => [
            'leads.read', 'leads.write', 'customers.read', 'customers.write', 'vendors.read', 'vendors.write',
            'products.read', 'products.write', 'orders.read', 'quotes.read',
        ],
        'logistique' => [
            'logistics.dashboard.read',
            'logistics.shipments.read', 'logistics.shipments.write',
            'logistics.tracking.read',
            'logistics.incidents.read', 'logistics.incidents.write',
            'logistics.drivers.read', 'logistics.drivers.write',
            'logistics.returns.read', 'logistics.returns.write',
            'logistics.zones.read', 'logistics.zones.write',
            'logistics.pricing.read', 'logistics.pricing.write',
        ],
    ],

    'route_permissions' => [
        'support.tickets.create' => 'tickets.write',
        'support.tickets.store' => 'tickets.write',
        'support.tickets.update' => 'tickets.write',
        'support.tickets.reply' => 'tickets.write',
        'support.tickets.*' => 'tickets.read',
        'support.messages.*' => 'messages.read',
        'support.clients.*' => 'customers.read',
        'support.vendors.*' => 'vendors.read',
        'support.orders.*' => 'orders.read',
        'support.payments.*' => 'payments.read',
        'support.deliveries.*' => 'deliveries.read',
        'support.incidents.*' => 'deliveries.read',
        'support.returns.*' => 'returns.read',
        'support.disputes.*' => 'disputes.read',

        'support.ai-agents.update' => 'support.ai.agents.manage',
        'support.ai-agents.*' => 'support.ai.agents.read',
        'support.conversations.store' => 'support.ai.conversations.respond',
        'support.conversations.reply' => 'support.ai.conversations.respond',
        'support.conversations.ai-reply' => 'support.ai.conversations.respond',
        'support.conversations.takeover' => 'support.ai.conversations.takeover',
        'support.conversations.handoff' => 'support.ai.conversations.takeover',
        'support.conversations.create-ticket' => 'support.ai.conversations.takeover',
        'support.conversations.resolve' => 'support.ai.conversations.takeover',
        'support.conversations.*' => 'support.ai.conversations.read',
        'support.calls.outbound' => 'support.ai.calls.initiate',
        'support.calls.callback' => 'support.ai.calls.initiate',
        'support.calls.transfer' => 'support.ai.calls.transfer',
        'support.calls.*' => 'support.ai.calls.read',
        'support.callbacks.store' => 'support.ai.calls.initiate',
        'support.callbacks.update' => 'support.ai.callbacks.manage',
        'support.callbacks.*' => 'support.ai.callbacks.read',
        'support.handoffs.accept' => 'support.ai.handoffs.manage',
        'support.handoffs.assign' => 'support.ai.handoffs.manage',
        'support.handoffs.resolve' => 'support.ai.handoffs.manage',
        'support.handoffs.*' => 'support.ai.handoffs.read',
        'support.knowledge.create' => 'support.ai.knowledge.manage',
        'support.knowledge.store' => 'support.ai.knowledge.manage',
        'support.knowledge.edit' => 'support.ai.knowledge.manage',
        'support.knowledge.update' => 'support.ai.knowledge.manage',
        'support.knowledge.destroy' => 'support.ai.knowledge.manage',
        'support.knowledge.*' => 'support.ai.knowledge.read',
        'support.ai-audit.*' => 'support.ai.supervision',

        'commercial.leads.create' => 'leads.write',
        'commercial.leads.store' => 'leads.write',
        'commercial.leads.update' => 'leads.write',
        'commercial.leads.activity' => 'leads.write',
        'commercial.leads.*' => 'leads.read',
        'commercial.handoffs.claim' => 'leads.write',
        'commercial.handoffs.resolve' => 'leads.write',
        'commercial.handoffs.*' => 'leads.read',
        'commercial.clients.create' => 'leads.write',
        'commercial.clients.store' => 'leads.write',
        'commercial.clients.*' => 'customers.read',
        'commercial.vendors.create' => 'leads.write',
        'commercial.vendors.store' => 'leads.write',
        'commercial.vendors.location.update' => 'vendors.write',
        'commercial.vendors.location.edit' => 'vendors.read',
        'commercial.vendors.*' => 'vendors.read',
        // Les profils commerciaux existants possèdent déjà leads.write. Utiliser
        // cette permission évite de les bloquer après l'ajout de ces écrans.
        'commercial.accounts.create' => 'leads.write',
        'commercial.accounts.store' => 'leads.write',
        'commercial.products.create' => 'leads.write',
        'commercial.products.store' => 'leads.write',
        'commercial.products.*' => 'products.read',
        'commercial.orders.*' => 'orders.read',
        'commercial.business.*' => 'quotes.read',
        'commercial.quotes.*' => 'quotes.read',

        'logistics.dashboard' => 'logistics.dashboard.read',
        'logistics.private-documents.*' => 'logistics.shipments.read',
        'logistics.shipments.export' => 'logistics.shipments.read',
        'logistics.shipments.details' => 'logistics.shipments.read',
        'logistics.shipments.status' => 'logistics.shipments.write',
        'logistics.shipments.assign' => 'logistics.shipments.write',
        'logistics.shipments.route' => 'logistics.shipments.write',
        'logistics.shipments' => 'logistics.shipments.read',
        'logistics.active-deliveries' => 'logistics.shipments.read',
        'logistics.tracking*' => 'logistics.tracking.read',
        'logistics.routes.*' => 'logistics.tracking.read',
        'logistics.driver.tracking' => 'logistics.tracking.read',
        'logistics.incidents.create' => 'logistics.incidents.write',
        'logistics.incidents.store' => 'logistics.incidents.write',
        'logistics.incidents.update' => 'logistics.incidents.write',
        'logistics.incidents.*' => 'logistics.incidents.read',
        'logistics.handoffs.claim' => 'logistics.incidents.write',
        'logistics.handoffs.status' => 'logistics.incidents.write',
        'logistics.handoffs.messages' => 'logistics.incidents.write',
        'logistics.handoffs.resolve' => 'logistics.incidents.write',
        'logistics.handoffs.*' => 'logistics.incidents.read',
        'logistics.drivers.update' => 'logistics.drivers.write',
        'logistics.drivers.access' => 'logistics.drivers.write',
        'logistics.drivers.store' => 'logistics.drivers.write',
        'logistics.drivers.*' => 'logistics.drivers.read',
        'logistics.drivers' => 'logistics.drivers.read',
        'logistics.returns' => 'logistics.returns.read',
        'logistics.returns.approve' => 'logistics.returns.write',
        'logistics.returns.reject' => 'logistics.returns.write',
        'logistics.returns.collect' => 'logistics.returns.write',
        'logistics.returns.notes' => 'logistics.returns.write',
        'logistics.returns.publish-decision' => 'logistics.returns.write',
        'logistics.returns.*' => 'logistics.returns.read',
        'logistics.zones.store' => 'logistics.zones.write',
        'logistics.zones.update' => 'logistics.zones.write',
        'logistics.zones.toggle' => 'logistics.zones.write',
        'logistics.zones.destroy' => 'logistics.zones.write',
        'logistics.zones.*' => 'logistics.zones.read',
        'logistics.zones' => 'logistics.zones.read',
        'logistics.ovanie-pricing.grids.store' => 'logistics.pricing.write',
        'logistics.ovanie-pricing.vehicle-tariffs.store' => 'logistics.pricing.write',
        'logistics.ovanie-pricing.matrices.store' => 'logistics.pricing.write',
        'logistics.ovanie-pricing.supplements.store' => 'logistics.pricing.write',
        'logistics.ovanie-pricing.calculate' => 'logistics.pricing.read',
        'logistics.ovanie-pricing.*' => 'logistics.pricing.read',

        'api.staff.support.tickets.store' => 'tickets.write',
        'api.staff.support.tickets.update' => 'tickets.write',
        'api.staff.support.tickets.reply' => 'tickets.write',
        'api.staff.support.tickets.*' => 'tickets.read',
        'api.staff.commercial.leads.store' => 'leads.write',
        'api.staff.commercial.leads.update' => 'leads.write',
        'api.staff.commercial.leads.activity' => 'leads.write',
        'api.staff.commercial.leads.*' => 'leads.read',
    ],
];
