@extends('layouts.guest')
@section('title', 'Conditions d’utilisation des cartes OVANIE')
@push('styles')<link rel="stylesheet" href="{{ asset('css/gift-card-guides.css') }}?v={{ filemtime(public_path('css/gift-card-guides.css')) }}">@endpush
@section('content')
<main class="gpg"><div class="gpg-wrap">
    <nav class="gpg-crumb"><a href="{{ route('home') }}">Accueil</a><span>›</span><a href="{{ route('gift-cards.index') }}">Cartes OVANIE</a><span>›</span><strong>Conditions</strong></nav>
    <header class="gpg-hero"><span class="gpg-pill">RÈGLES & CONDITIONS</span><h1>Conditions d’utilisation des cartes <em>OVANIE</em></h1><p>Ces règles s’appliquent aux bons d’achat, cartes cadeaux et cartes virtuelles. Elles garantissent une utilisation simple, sécurisée et transparente.</p></header>
    <section class="gpg-types"><article class="gpg-type is-active"><i><svg><use href="#guide-gift"/></svg></i><div><h3>Bon d’Achat</h3><p>Adapté aux achats professionnels et aux chantiers.</p></div></article><article class="gpg-type"><i><svg><use href="#guide-card"/></svg></i><div><h3>Carte Cadeau</h3><p>Une solution pratique à offrir à vos proches.</p></div></article><article class="gpg-type"><i><svg><use href="#guide-wallet"/></svg></i><div><h3>Carte Virtuelle</h3><p>Personnelle, rechargeable et disponible en ligne.</p></div></article></section>
    <h2 style="font-size:20px">Règles générales d’utilisation</h2>
    @php $rules=[['clock','Validité','La durée commence à compter de l’achat ou de l’activation selon le type de carte.'],['cart','Utilisation','La carte est utilisable sur OVANIE selon les conditions propres à chaque formule.'],['wallet','Solde restant','Le montant non utilisé reste disponible jusqu’à expiration.'],['card','Paiement mixte','Si le solde est insuffisant, le complément peut être réglé avec un autre moyen.'],['shield','Remboursement','Les cartes ne sont ni remboursables en espèces ni échangeables contre de l’argent.'],['refresh','Rechargement','Seules les cartes virtuelles rechargeables peuvent être rechargées.'],['key','Sécurité','Le code et le PIN sont générés après paiement confirmé.'],['headset','Perte ou oubli','Retrouvez vos cartes depuis votre espace client.'],['gift','Usage personnel ou cadeau','Utilisez la carte pour vous-même ou offrez-la à un bénéficiaire.']]; @endphp
    <section class="gpg-info">@foreach($rules as $rule)<article class="gpg-info-card"><i><svg class="gpg-svg"><use href="#guide-{{ $rule[0] }}"/></svg></i><div><b>{{ $rule[1] }}</b><p>{{ $rule[2] }}</p></div></article>@endforeach</section>
    <h2 class="gpg-title">Résumé par type de carte</h2>
    <table class="gpg-table"><thead><tr><th>Règle</th><th>Bon d’Achat</th><th>Carte Cadeau</th><th>Carte Virtuelle</th></tr></thead><tbody><tr><td>Validité</td><td>{{ $purchaseValidity }}</td><td>{{ $giftValidity }}</td><td>{{ $virtualValidity }}</td></tr><tr><td>Rechargeable</td><td>Non</td><td>Non</td><td>Selon la formule</td></tr><tr><td>Paiement mixte</td><td>Oui</td><td>Oui</td><td>Oui</td></tr><tr><td>Disponible après paiement</td><td>Oui</td><td>Oui</td><td>Oui</td></tr><tr><td>Remboursable en espèces</td><td>Non</td><td>Non</td><td>Non</td></tr><tr><td>Consultation du solde</td><td>Espace client</td><td>Espace client</td><td>Espace client</td></tr></tbody></table>
    <section class="gpg-faq"><h2>Questions fréquentes</h2><details><summary>Quand commence la validité de ma carte ?</summary><p>À la date d’achat ou d’activation indiquée pour la formule sélectionnée.</p></details><details><summary>Puis-je utiliser ma carte en plusieurs fois ?</summary><p>Oui, tant qu’un solde est disponible et que la carte demeure valide.</p></details><details><summary>Que se passe-t-il si ma commande dépasse le solde ?</summary><p>Vous pouvez régler le complément avec un moyen de paiement disponible.</p></details><details><summary>La carte est-elle remboursable ?</summary><p>Non, elle n’est pas échangeable ou remboursable en espèces.</p></details></section>
    <section class="gpg-cta"><div><h2>Besoin d’aide avant d’acheter ?</h2><p>Consultez le guide ou découvrez toutes les cartes OVANIE.</p></div><div class="gpg-actions"><a class="gpg-btn alt" href="{{ route('gift-cards.how-it-works') }}">Voir comment ça marche</a><a class="gpg-btn" href="{{ route('gift-cards.index') }}">Découvrir les cartes</a></div></section>
</div></main>
@include('gift-cards.partials.guide-icons')
@endsection
