@extends('layouts.guest')
@php
    $phone = (string) config('public_contact.phone_display', '01 61 78 00 00');
    $phoneHref = (string) config('public_contact.phone_e164', '+2250161780000');
    $email = (string) config('public_contact.email', 'contact@ovanie.com');
    $wa = (string) config('public_contact.whatsapp_url', 'https://wa.me/2250161781818?text=Bonjour%20OVANIE%2C%20j%E2%80%99ai%20besoin%20d%E2%80%99assistance.');
    $waLabel = (string) config('public_contact.whatsapp_label', 'Discutez avec un conseiller');
@endphp
@section('title','Contact OVANIE')
@push('styles')<link rel="stylesheet" href="{{asset('css/support-pages.css')}}?v={{filemtime(public_path('css/support-pages.css'))}}"><style>.ct-hero{min-height:390px;padding:48px;display:flex;align-items:center;border-radius:17px;background:#062d65 url('{{asset('images/support-pages/support-hero.png')}}') center/cover;color:#fff}.ct-hero>div{width:52%}.ct-hero h1{margin:0 0 18px;font-size:55px}.ct-hero h1 em{color:#ff6500;font-style:normal}.ct-hero p{font-size:17px;line-height:1.6}.ct-topics{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:28px 0}.ct-topics div{padding:22px;text-align:center;border:1px solid #dce5ef;border-radius:12px;background:#fff}.ct-topics i{width:48px;color:#073d81}.ct-topics b{display:block;margin-top:10px;font-size:12px}.ct-layout{display:grid;grid-template-columns:1.2fr .85fr;gap:25px}.ct-form,.ct-side>section{padding:28px;border:1px solid #dce5ef;border-radius:14px;background:#fff}.ct-form h2{margin-top:0}.ct-fields{display:grid;grid-template-columns:1fr 1fr;gap:16px}.ct-form label{display:block;margin:14px 0 6px;font-size:11px;font-weight:800}.ct-form input,.ct-form select,.ct-form textarea{width:100%;padding:13px;border:1px solid #ccd8e6;border-radius:7px}.ct-form textarea{min-height:150px;resize:vertical}.ct-form button{width:100%;height:50px;margin-top:17px;border:0;border-radius:7px;background:#ff6500;color:#fff;font-weight:800}.ct-side{display:grid;gap:18px}.ct-wa{background:#f2fff7!important}.ct-wa strong{display:block;color:#08a84f;font-size:28px;margin:14px 0}.ct-wa a{display:block;padding:14px;text-align:center;border-radius:7px;background:#08a84f;color:#fff;text-decoration:none;font-weight:800}.ct-side p{color:#607089;font-size:11px;line-height:1.6}.ct-side h2{margin-top:0}@media(max-width:800px){.ct-topics{grid-template-columns:repeat(2,1fr)}.ct-layout,.ct-fields{grid-template-columns:1fr}.ct-hero>div{width:100%}.ct-hero{padding:28px;background-position:65%}.ct-hero h1{font-size:40px}}</style>@endpush
@section('content')<main class="sp"><div class="sp-shell"><nav class="sp-crumb"><a href="{{route('home')}}">Accueil</a><span>›</span><b>Contact</b></nav>
<section class="ct-hero"><div><h1>Contact <em>OVANIE</em></h1><p>Besoin d’aide ? Notre équipe est là pour vous accompagner.</p><p>Pour toute question concernant vos commandes, paiements, livraisons, produits ou votre compte, contactez-nous.</p><div class="ct-hero-badges"><span><i data-lucide="shield-check"></i>Plateforme sécurisée</span><span><i data-lucide="headset"></i>Équipe à votre écoute</span><span><i data-lucide="badge-check"></i>Satisfaction garantie</span></div></div></section>
<h2 class="sp-center-title">Besoin d’aide ?</h2><section class="ct-topics">@foreach([['shopping-bag','Commande'],['credit-card','Paiement'],['truck','Livraison'],['package','Produit'],['user','Compte'],['message-circle','Autre problème']] as $item)<div><i data-lucide="{{$item[0]}}"></i><b>{{$item[1]}}</b></div>@endforeach</section>
<section class="ct-layout"><div class="ct-form"><h2>Envoyez-nous votre message</h2><p>Notre équipe vous répondra rapidement.</p>@if(session('success'))<div class="alert success">{{session('success')}}</div>@endif @if($errors->any())<div class="alert error">{{$errors->first()}}</div>@endif<form action="{{route('contact.send')}}" method="POST">@csrf<div class="ct-fields"><div><label for="name">Nom complet *</label><input id="name" name="name" value="{{old('name')}}" required placeholder="Votre nom complet"></div><div><label for="email">Adresse e-mail *</label><input id="email" type="email" name="email" value="{{old('email')}}" required placeholder="exemple@email.com"></div></div><label for="subject">Sujet *</label><select id="subject" name="subject" required><option value="">Sélectionnez un sujet</option>@foreach(['Commande','Paiement','Livraison','Produit','Compte','Autre problème'] as $s)<option @selected(old('subject')===$s)>{{$s}}</option>@endforeach</select><label for="message">Message *</label><textarea id="message" name="message" required placeholder="Décrivez votre demande en détail...">{{old('message')}}</textarea><button type="submit">Envoyer le message</button></form></div><aside class="ct-side"><section class="ct-wa"><h2>WhatsApp OVANIE</h2><p>Le moyen le plus rapide pour nous contacter.</p><a href="{{$wa}}" target="_blank" rel="noopener">{{$waLabel}}</a></section><section><h2>Téléphone</h2><p><a href="tel:{{$phoneHref}}">{{$phone}}</a><br>Lundi – Vendredi : 08h00 – 18h00</p></section><section><h2>Horaires de réponse</h2><p><b>Lundi – Vendredi :</b> 08h00 – 18h00<br><b>Samedi :</b> 08h00 – 13h00<br><b>Dimanche :</b> Fermé</p></section><section><h2>Contact par e-mail</h2><p><a href="mailto:{{$email}}">{{$email}}</a><br>Réponse sous 24 heures ouvrées.</p></section></aside></section>
</div></main>@endsection
@push('styles')<style>.ct-hero{background-color:#062d65;background-image:linear-gradient(90deg,rgba(6,45,101,.32),rgba(6,45,101,0)),url('{{asset('images/support-pages/support-hero.png')}}');background-repeat:no-repeat;background-position:center,right center;background-size:100% 100%,auto 100%}@media(max-width:800px){.ct-hero{background-position:center,right center;background-size:100% 100%,auto 100%}}</style>@endpush
@push('styles')<style>.ct-hero{background-image:linear-gradient(90deg,rgba(3,34,75,.28),rgba(3,34,75,0)),url('{{asset('images/support-pages/support-hero.png')}}');background-size:100% 100%;background-position:center}.ct-hero-badges{display:flex;gap:10px;margin-top:28px}.ct-hero-badges span{padding:12px 14px;display:flex;align-items:center;gap:8px;border:1px solid rgba(255,255,255,.2);border-radius:7px;background:rgba(255,255,255,.06);font-size:10px;font-weight:800}.ct-hero-badges i{width:24px;color:#fff}@media(max-width:800px){.ct-hero{background-size:cover;background-position:center}.ct-hero-badges{display:grid;grid-template-columns:1fr}}</style>@endpush
