@extends('layouts.logistics-operations')
@section('title','Fiche livreur')
@section('page-class','ops-directory directory-driver-profile')
@include('logistics.directory.assets')
@section('content')
<style>
.directory-driver-profile .driver-zones-card{display:flex;flex-direction:column;gap:12px}.directory-driver-profile .driver-zones-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 14px;border:1px solid #dbe7f3;border-radius:12px;background:#f8fbff}.directory-driver-profile .driver-zones-meta{display:flex;align-items:center;gap:12px;min-width:0}.directory-driver-profile .driver-zones-count{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;background:#e7f8ef;color:#008e57;font-weight:800;font-size:18px;flex:0 0 auto}.directory-driver-profile .driver-zones-meta strong{display:block;color:#0b1d4d;font-size:14px}.directory-driver-profile .driver-zones-meta small{display:block;margin-top:2px;color:#64748b;font-size:12px}.directory-driver-profile .driver-zones-city{display:inline-flex;align-items:center;min-height:30px;padding:0 11px;border-radius:999px;background:#eef5ff;color:#2459a9;font-size:12px;font-weight:700;white-space:nowrap}.directory-driver-profile .driver-zones-map{height:245px!important;border:1px solid #dbe7f3;border-radius:12px;overflow:hidden;background:#eef4f8}.directory-driver-profile .driver-zones-footer{display:flex;flex-wrap:wrap;gap:7px;padding:2px 1px 0}.directory-driver-profile .driver-zones-footer .directory-zone-pill{margin:0;background:#f3f7fb;border:1px solid #dce7f2;color:#274060}.directory-driver-profile .driver-zones-empty{padding:14px;border:1px dashed #cbd8e6;border-radius:10px;color:#64748b;background:#fafcff}@media(max-width:900px){.directory-driver-profile .driver-zones-toolbar{align-items:flex-start}.directory-driver-profile .driver-zones-map{height:220px!important}}
</style>
@php
use App\ViewModels\LogisticsDirectoryData as D;
[$status,$tone]=D::driverStatus($driver);
$profile=$driver->profile??[];
$location=$driver->currentLocation;
$driverZones=isset($interventionZoneCommunes) && $interventionZoneCommunes->isNotEmpty()
    ? $interventionZoneCommunes->pluck('name')->values()->all()
    : $driver->interventionZones();
$done=$driver->assignments->where('status','delivered')->count();
$rate=$driver->assignments_count?round($done/$driver->assignments_count*100):null;
$hasActiveMission=(int)($driver->active_assignments_count??0)>0;
$vehicleLabels=['moto'=>'Moto','tricycle'=>'Tricycle','pickup'=>'Pickup','camion_3t'=>'Camion 3T','camion_10t'=>'Camion 10T'];
$vehicleLabel=$vehicleLabels[$driver->vehicle]??ucfirst(str_replace('_',' ',(string)$driver->vehicle));
$dayLabels=['lundi'=>'Lun','mardi'=>'Mar','mercredi'=>'Mer','jeudi'=>'Jeu','vendredi'=>'Ven','samedi'=>'Sam','dimanche'=>'Dim'];
$availabilityDays=collect($profile['availability_days']??[])->map(fn($day)=>$dayLabels[$day]??ucfirst((string)$day))->values();
@endphp
<x-operations.directory-header title="Fiche livreur" section="Livreurs" :url="route('logistics.drivers')" subtitle="Détails du profil, disponibilité, véhicule, performances et historique de missions"><button class="ops-button" data-directory-open="driver-edit"><x-operations.icon name="edit"/>Modifier</button>@if(in_array($driver->onboarding_status, ['active','suspended']))<form method="post" action="{{ route('logistics.drivers.update',$driver) }}">
@csrf @method('PATCH')<input type="hidden" name="toggle_active" value="1"><button class="ops-button">{{ $driver->is_active?'Désactiver':'Activer' }} le compte</button></form>@endif<button class="ops-button" data-directory-open="driver-access" aria-label="Connexion mobile">Connexion mobile</button><form method="post" action="{{ route('logistics.drivers.destroy',$driver) }}" onsubmit="return confirm('Supprimer définitivement le compte de {{ $driver->name }} ? Cette action est irréversible.');">
@csrf @method('DELETE')<button class="ops-button ops-button-danger">Supprimer le compte</button></form></x-operations.directory-header>

<div class="directory-profile"><aside class="directory-profile-nav"><a class="ops-button" href="{{ route('logistics.drivers') }}">← Retour à la liste</a><div class="directory-person">@if($driver->avatar)<img class="directory-avatar" src="{{ Storage::disk('public')->url($driver->avatar) }}" alt="Photo de {{ $driver->name }}">@else<span class="directory-avatar">{{ $driver->initials }}</span>@endif<span><strong>{{ $driver->name }}</strong><br><x-operations.tag :tone="$tone">{{ $status }}</x-operations.tag><small>{{ D::ref($driver,'LIV') }}</small></span></div>
@foreach(['overview'=>['warehouse',"Vue d’ensemble"],'personal'=>['user','Informations personnelles'],'vehicle'=>['truck','Véhicule'],'availability'=>['clock','Disponibilité'],'performance'=>['chart','Performances'],'history'=>['clock','Historique des missions'],'settings'=>['settings','Paramètres']] as $id=>[$icon,$label])<a href="#{{ $id }}" class="{{ $loop->first?'active':'' }}"><x-operations.icon :name="$icon"/>{{ $label }}</a>
@endforeach
</aside><div class="directory-stack" id="overview">
<div class="directory-profile-top"><x-operations.panel id="personal"><div class="directory-profile-hero">
@if($driver->avatar)<img class="directory-avatar hero" src="{{ Storage::disk('public')->url($driver->avatar) }}" alt="{{ $driver->name }}">
@else<span class="directory-avatar hero">{{ $driver->initials }}</span>
@endif
<div><h2>{{ $driver->name }}</h2><x-operations.tag :tone="$driver->is_active?'green':'slate'">{{ $driver->is_active?'Livreur actif':'Compte désactivé' }}</x-operations.tag><p>ID : {{ D::ref($driver,'LIV') }} <span class="directory-rating">★ {{ $driver->rating!==null ? number_format($driver->rating,1,',',' ') : '—' }}</span></p><p><x-operations.icon name="phone"/>{{ $driver->phone }}</p>@if(filled($driver->email))<p><x-operations.icon name="mail"/>{{ $driver->email }}</p>@endif<p><x-operations.icon name="pin"/>{{ implode(', ',array_slice($driverZones,0,2)) }}@if(count($driverZones)>2) +{{ count($driverZones)-2 }}@endif, Abidjan</p><p><x-operations.icon name="calendar"/>Inscrit le {{ $driver->created_at?->format('d/m/Y') }}</p></div><div class="directory-profile-status">Statut actuel<p><x-operations.tag :tone="$tone">{{ $status }}</x-operations.tag></p><p>{{ $driver->last_seen_at?->locale('fr')->diffForHumans()??'Aucune activité récente' }}</p>@if($hasActiveMission)<a class="ops-button ops-button-primary" href="{{ route('logistics.tracking.driver',$driver) }}"><x-operations.icon name="pin"/>Voir sa position en temps réel</a>@endif</div></div></x-operations.panel><x-operations.panel title="Disponibilité" icon="clock" id="availability"><x-slot:actions><button data-directory-open="driver-edit">Modifier</button></x-slot:actions><div class="directory-soft"><strong>Jours de travail</strong>@if($availabilityDays->isNotEmpty())<div class="directory-zone-summary" style="margin-top:10px">@foreach($availabilityDays as $day)<span class="directory-zone-pill">{{ $day }}</span>@endforeach</div>@else<p>Jours de travail non renseignés</p>@endif</div></x-operations.panel></div>
<div class="directory-two"><x-operations.panel title="Véhicule du livreur" icon="truck" id="vehicle"><x-slot:actions><button data-directory-open="driver-edit">Modifier</button></x-slot:actions><div class="directory-vehicle">@if($driver->vehiclePhotoPath())<a href="{{ Storage::disk('public')->url($driver->vehiclePhotoPath()) }}" target="_blank" rel="noopener"><img src="{{ Storage::disk('public')->url($driver->vehiclePhotoPath()) }}" alt="Photo du véhicule du livreur" style="width:200px;max-width:100%;height:160px;object-fit:contain;border-radius:12px"></a>@else<div class="directory-placeholder"><span>Aucune photo transmise</span></div>@endif<div><h3>{{ $vehicleLabel }}</h3><dl class="directory-facts"><dt>Véhicule</dt><dd>{{ $vehicleLabel }}</dd><dt>Immatriculation</dt><dd>{{ $profile['plate']??'Non renseignée' }}</dd></dl></div></div></x-operations.panel><x-operations.panel title="Zones d’intervention" icon="pin"><x-slot:actions><button data-directory-open="driver-edit">Modifier</button></x-slot:actions><div class="driver-zones-card"><div class="driver-zones-toolbar"><div class="driver-zones-meta"><span class="driver-zones-count">{{ count($driverZones) }}</span><div><strong>{{ count($driverZones) > 1 ? 'Zones actives' : 'Zone active' }}</strong><small>Périmètre opérationnel attribué au livreur</small></div></div><span class="driver-zones-city">Abidjan</span></div>@if(count($driverZones))<div class="directory-map driver-zones-map" data-directory-map='@json($interventionZonePoints ?? [])'></div><div class="driver-zones-footer">@foreach($driverZones as $zone)<span class="directory-zone-pill">{{ $zone }}</span>@endforeach</div>@else<div class="driver-zones-empty">Aucune zone d’intervention n’est encore attribuée à ce livreur.</div>@endif</div></x-operations.panel></div>
<x-operations.panel title="Performances du livreur" icon="chart" id="performance"><div class="directory-kpis">
@foreach([['check','Missions effectuées',$done,'green'],['clock','Taux de livraison',$rate===null?'—':$rate.' %','blue'],['star','Note moyenne',$driver->rating!==null?number_format($driver->rating,1,',',' '):'—','orange'],['alert','Incidents',$profile['incident_count']??'—','green'],['return','Retours',$profile['return_count']??'—','red']] as [$icon,$label,$value,$color])<x-operations.kpi :icon="$icon" :label="$label" :value="$value" :tone="$color"/>
@endforeach
</div></x-operations.panel>
<div class="directory-two"><x-operations.panel title="Dernière position GPS" icon="target"><x-slot:actions><x-operations.tag :tone="$driver->is_online?'green':'slate'">{{ $driver->is_online?'En ligne':'Hors ligne' }}</x-operations.tag></x-slot:actions><p>{{ $location?->recorded_at?->format('d/m/Y à H:i')??'Aucune position transmise' }}</p><div class="directory-map-layout"><div class="directory-map large" data-directory-map="{{ json_encode($location?[['lat'=>$location->latitude,'lng'=>$location->longitude,'label'=>$driver->name]]:[]) }}"></div><dl class="directory-facts"><dt>Zones</dt><dd>{{ $driver->interventionZonesLabel(2) }}</dd><dt>Vitesse</dt><dd>{{ $location?->speed??'—' }} km/h</dd><dt>Batterie</dt><dd>{{ $location?->battery_level??'—' }} %</dd><dt>Précision GPS</dt><dd>{{ $location?->accuracy??'—' }} m</dd></dl></div>@if($hasActiveMission)<a class="ops-button" href="{{ route('logistics.tracking.driver',$driver) }}">Ouvrir dans le centre de suivi GPS ↗</a>@endif</x-operations.panel><x-operations.panel title="Historique des dernières missions" icon="tour" id="history"><x-slot:actions><a href="{{ route('logistics.shipments',['q'=>$driver->name]) }}">Voir tout</a></x-slot:actions><div class="directory-table-wrap"><table class="directory-table"><thead><tr><th>#</th><th>Date</th><th>Collecte</th><th>Destination</th><th>Statut</th></tr></thead><tbody>
@forelse($missions as $m)<tr><td><a class="directory-ref" title="{{ $m->mission_number }}" href="{{ route('logistics.shipments.details',$m->order_item_id) }}">{{ Str::limit($m->mission_number,14) }}</a></td><td>{{ $m->created_at?->format('d/m/Y') }}</td><td>{{ $m->orderItem?->product?->shop?->commune??'—' }}</td><td>{{ $m->orderItem?->order?->delivery_commune??'—' }}</td><td><x-operations.tag :tone="$m->status==='delivered'?'green':'blue'">{{ $m->status==='delivered'?'Livrée':'En cours' }}</x-operations.tag></td></tr>
@empty<tr><td colspan="5">Aucune mission.</td></tr>
@endforelse
</tbody></table></div></x-operations.panel></div>
<x-operations.panel title="Notes et commentaires" icon="list" id="settings"><div class="directory-notes">
@forelse($profile['notes']??[] as $note)<div><span class="directory-avatar">RL</span><span>{{ $note['text'] }}<small>Par {{ $note['author'] }} — {{ \Carbon\Carbon::parse($note['at'])->format('d/m/Y H:i') }}</small></span></div>
@empty<p>Aucune note.</p>
@endforelse
</div><details class="directory-note-disclosure"><summary class="directory-link">+ Ajouter une note</summary><form class="directory-form" action="{{ route('logistics.drivers.update',$driver) }}" method="post">
@csrf @method('PATCH')<label>Ajouter une note<textarea name="note" required maxlength="1000"></textarea></label><button class="ops-button">Enregistrer la note</button></form></details></x-operations.panel>
</div></div>
@include('logistics.directory.driver-form',['editing'=>true])
@include('logistics.directory.driver-connection')
@endsection
