@extends('admin.layouts.app')
@section('title','Cartes cadeaux')
@section('page-title','Cartes cadeaux OVANIE')
@push('styles')<style>.gc-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.gc-stat,.gc-box{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:18px}.gc-stat strong{font-size:27px;display:block}.gc-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.gc-table{width:100%;border-collapse:collapse}.gc-table th,.gc-table td{padding:10px;border-bottom:1px solid #eee;text-align:left}.gc-form input{width:100%;padding:8px;border:1px solid #ddd;border-radius:7px}.gc-actions{display:flex;gap:6px}.gc-actions button{padding:7px 10px;border:0;border-radius:7px;cursor:pointer}.danger{background:#b91c1c;color:#fff}.good{background:#15803d;color:#fff}@media(max-width:900px){.gc-stats{grid-template-columns:1fr 1fr}.gc-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
<div class="gc-stats"><div class="gc-stat"><span>Cartes actives</span><strong>{{ number_format($stats['active']) }}</strong></div><div class="gc-stat"><span>Cartes bloquées</span><strong>{{ number_format($stats['blocked']) }}</strong></div><div class="gc-stat"><span>Solde total émis</span><strong>{{ number_format($stats['balance'],0,',',' ') }} F</strong></div><div class="gc-stat"><span>Mouvements</span><strong>{{ number_format($stats['transactions']) }}</strong></div></div>
<div class="gc-grid"><section class="gc-box"><h2>Cartes émises</h2><form method="GET" style="display:flex;gap:8px;margin-bottom:12px"><input name="search" value="{{ request('search') }}" placeholder="Code, bénéficiaire, téléphone"><select name="status"><option value="">Tous les statuts</option>@foreach(['active','blocked','expired','exhausted'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ $s }}</option>@endforeach</select><button>Filtrer</button></form><div style="overflow:auto"><table class="gc-table"><thead><tr><th>Code</th><th>Type</th><th>Solde</th><th>Statut</th><th>Action</th></tr></thead><tbody>@foreach($cards as $card)<tr><td>{{ $card->code }}</td><td>{{ $card->product?->name }}</td><td>{{ number_format($card->availableBalance(),0,',',' ') }}</td><td>{{ $card->status }}</td><td class="gc-actions">@if($card->status==='blocked')<form method="POST" action="{{ route('admin.gift-cards.unblock',$card) }}">@csrf<button class="good">Réactiver</button></form>@else<form method="POST" action="{{ route('admin.gift-cards.block',$card) }}">@csrf<button class="danger">Bloquer</button></form>@endif</td></tr>@endforeach</tbody></table></div>{{ $cards->links() }}</section>
<section class="gc-box"><h2>Modèles de cartes</h2>@foreach($products as $product)<form class="gc-form" method="POST" action="{{ route('admin.gift-cards.products.update',$product) }}" style="border-bottom:1px solid #eee;padding:12px 0">@csrf @method('PATCH')<strong>{{ $product->name }}</strong><p><label>Nom<input name="name" value="{{ $product->name }}"></label></p><p><label>Prix d’activation<input type="number" name="activation_price" value="{{ (float)$product->activation_price }}"></label></p><p><label>Solde initial<input type="number" name="initial_balance" value="{{ (float)$product->initial_balance }}"></label></p><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><label>Validité jours<input type="number" name="validity_days" value="{{ $product->validity_days }}"></label><label>Validité mois<input type="number" name="validity_months" value="{{ $product->validity_months }}"></label></div><p><label>Plafond recharge<input type="number" name="max_total_recharge" value="{{ $product->max_total_recharge }}"></label></p><label><input type="checkbox" name="is_active" value="1" @checked($product->is_active)> Actif</label><button type="submit" style="margin-left:10px">Enregistrer</button></form>@endforeach</section></div>
@endsection
