.account-shell{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:18px;align-items:start}
.account-form{overflow:hidden;padding:0}
.account-hero{padding:22px 24px;background:linear-gradient(135deg,#10264f 0%,#1d4b86 100%);color:#fff}
.account-hero-badge{display:inline-flex;align-items:center;gap:7px;margin-bottom:10px;padding:6px 9px;border-radius:999px;background:rgba(255,255,255,.12);font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}
.account-hero h2{margin:0;font-size:19px;line-height:1.25}
.account-hero p{max-width:760px;margin:7px 0 0;color:#dbe8f8;font-size:10.5px;line-height:1.6}
.account-body{padding:22px 24px}
.form-errors{margin-bottom:18px;padding:13px 15px;border:1px solid #fecaca;border-radius:11px;background:#fff5f5;color:#a61b1b}
.form-errors strong{display:block;font-size:10.5px}.form-errors ul{margin:7px 0 0;padding-left:18px;font-size:9.5px;line-height:1.55}
.account-section{padding:22px 0;border-top:1px solid #e5ebf3}.account-section:first-of-type{padding-top:0;border-top:0}
.section-heading{display:flex;align-items:flex-start;gap:11px;margin-bottom:15px}
.section-number{width:31px;height:31px;display:grid;place-items:center;flex:0 0 31px;border-radius:9px;background:#edf4ff;color:#174b8f;font-size:10px;font-weight:900}
.section-heading h3{margin:0;color:#10264f;font-size:14px}.section-heading p{margin:4px 0 0;color:#7a879a;font-size:9.5px;line-height:1.5}
.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.form-grid .full{grid-column:1/-1}
.field{display:flex;flex-direction:column;gap:6px;min-width:0}.field label{color:#2d4669;font-size:9.8px;font-weight:800}
.field input,.field select,.field textarea{width:100%;border:1px solid #d9e2ed;border-radius:9px;background:#fff;color:#17345f;font-size:10.5px;outline:none;transition:.18s ease}
.field input,.field select{height:43px;padding:0 11px}.field textarea{min-height:100px;padding:11px;resize:vertical;line-height:1.55}
.field input:focus,.field select:focus,.field textarea:focus{border-color:#f97316;box-shadow:0 0 0 3px rgba(249,115,22,.09)}
.required{color:#dc2626}.field-help{color:#8793a5;font-size:8.7px;line-height:1.45}.field-error{color:#be123c;font-size:8.8px}
.phone-row{display:grid;grid-template-columns:116px minmax(0,1fr);gap:8px}
.password-wrap{position:relative}.password-wrap input{padding-right:44px}.password-toggle{position:absolute;right:4px;top:4px;width:35px;height:35px;border:0;border-radius:7px;background:#f2f6fb;color:#61728b;cursor:pointer}.password-toggle svg{width:18px}
.choice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.choice-card{display:flex;align-items:flex-start;gap:10px;padding:13px;border:1px solid #dce4ee;border-radius:11px;background:#fff;cursor:pointer}.choice-card:has(input:checked){border-color:#f97316;background:#fff9f4;box-shadow:0 0 0 3px rgba(249,115,22,.07)}.choice-card input{width:17px!important;height:17px!important;margin:2px 0 0!important;flex:0 0 17px}.choice-card strong{display:block;color:#17345f;font-size:10.5px}.choice-card small{display:block;margin-top:3px;color:#7a879a;font-size:9px;line-height:1.45}
.category-picker{position:relative}.category-button{position:relative;width:100%;height:43px;border:1px solid #d9e2ed;border-radius:9px;background:#fff;padding:0 40px 0 11px;text-align:left;color:#17345f;font-size:10.5px;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.category-button:after{content:'⌄';position:absolute;right:14px;top:10px;font-size:17px;color:#6d7b8e}.category-menu{position:absolute;z-index:45;left:0;right:0;top:calc(100% + 6px);padding:9px;border:1px solid #dbe3ed;border-radius:11px;background:#fff;box-shadow:0 18px 40px rgba(16,38,79,.18)}.category-menu.hidden{display:none}.category-menu input{height:39px!important;margin-bottom:8px}.category-options{max-height:230px;overflow:auto}.category-option{display:block;width:100%;border:0;border-radius:7px;background:#fff;padding:9px;text-align:left;color:#294364;font-size:9.8px;cursor:pointer}.category-option:hover{background:#eef4ff;color:#075ee8}
.form-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:16px;padding-top:18px;border-top:1px solid #e5ebf3}
.account-side{position:sticky;top:84px;display:grid;gap:14px}.side-card{padding:18px}.side-card h3{margin:0;color:#10264f;font-size:13px}.side-card>p{margin:6px 0 0;color:#77859a;font-size:9.5px;line-height:1.55}.side-list{display:grid;gap:13px;margin-top:16px}.side-item{display:grid;grid-template-columns:29px 1fr;gap:10px}.side-item-number{width:29px;height:29px;display:grid;place-items:center;border-radius:8px;background:#edf4ff;color:#174b8f;font-size:9px;font-weight:900}.side-item strong{display:block;color:#17345f;font-size:9.8px}.side-item small{display:block;margin-top:2px;color:#7d899b;font-size:8.7px;line-height:1.45}
.side-note{display:flex;align-items:flex-start;gap:9px;padding:13px;border:1px solid #fed7aa;border-radius:11px;background:#fff8ed;color:#8c4a0a;font-size:9.4px;line-height:1.55}.side-note svg{width:17px;flex:0 0 17px}.side-note.client{border-color:#d8e5f5;background:#f6f9fd;color:#405d83}.hidden{display:none!important}
@media(max-width:1050px){.account-shell{grid-template-columns:1fr}.account-side{position:static;grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:700px){.account-body{padding:17px}.account-hero{padding:19px}.form-grid,.choice-grid,.account-side{grid-template-columns:1fr}.form-grid .full{grid-column:auto}.phone-row{grid-template-columns:105px 1fr}.form-actions{position:sticky;bottom:7px;z-index:20;padding:8px;border:1px solid #e1e8f1;border-radius:10px;background:rgba(255,255,255,.97);box-shadow:0 10px 28px rgba(16,38,79,.16)}.form-actions .btn{flex:1}.field input,.field select,.field textarea{font-size:16px}.category-menu{position:fixed;left:12px;right:12px;top:50%;transform:translateY(-50%);max-width:440px;margin:auto}.category-options{max-height:55vh}}
